# **Pandas Foundations**

In [114]:
import numpy as np
import pandas as pd
import pyarrow as pa

## **Series**

In [2]:
# Building a Series from a python list
pd.Series([0, 1, 2])

0    0
1    1
2    2
dtype: int64

In [3]:
# Building a Series from a python tuple
pd.Series((0, 1, 2))

0    0
1    1
2    2
dtype: int64

In [4]:
# Generating a sample of data
pd.Series(range(0, 7, 2))

0    0
1    2
2    4
3    6
dtype: int64

In [9]:
# in all time pandas try to infer the data type for us but in some cases provides the right dtpe can save memory
pd.Series(range(3), dtype="int8")

0    0
1    1
2    2
dtype: int8

In [10]:
# if the property of the name not specified then will set to None
pd.Series(["apple", "banana", "orange"], name="fruit")

0     apple
1    banana
2    orange
Name: fruit, dtype: object

## **DataFrame**

In [11]:
# constructing a DataFrame from a two-dimensional array
pd.DataFrame([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [12]:
pd.DataFrame([
    [1, 2],
    [3, 4]
], columns=["col_a", "col_b"])

   col_a  col_b
0      1      2
1      3      4

In [13]:
pd.DataFrame({
    "first_name": ["John", "Alex"],
    "last_name": ["Smith", "Doe"]
})

  first_name last_name
0       John     Smith
1       Alex       Doe

In [17]:
# DataFram Accept any sequence of values
ser1 = pd.Series(range(3), dtype="int8", name="col_int8")
ser2 = pd.Series(range(3), dtype="int16", name="col_int16")
pd.DataFrame({ser1.name: ser1, ser2.name: ser2})

   col_int8  col_int16
0         0          0
1         1          1
2         2          2

## **Index**

In [19]:
pd.Series([4, 4, 2], index=["cat", "dog", "fish"])

cat     4
dog     4
fish    2
dtype: int64

In [20]:
index = pd.Index(["dog", "cat", "fish"], name="animal")
pd.Series([4, 4, 0], name="num_legs", index=index)

animal
dog     4
cat     4
fish    0
Name: num_legs, dtype: int64

In [21]:
pd.DataFrame([
    [24, 183],
    [42, 160]
], index=["John", "Doe"], columns=["Age", "Height_cm"])

      Age  Height_cm
John   24        183
Doe    42        160

## **Series attributes**

In [22]:
index = pd.Index(["dog", "cat", "fish"], name="animal")
ser = pd.Series([4, 4, 0], name="num_legs", index=index)
ser

animal
dog     4
cat     4
fish    0
Name: num_legs, dtype: int64

In [24]:
# data type of Serie
ser.dtype

dtype('int64')

In [25]:
# name of Serie
ser.name

'num_legs'

In [26]:
# acces the index
ser.index

Index(['dog', 'cat', 'fish'], dtype='object', name='animal')

In [27]:
# acces the name of the index
ser.index.name

'animal'

In [28]:
ser.shape

(3,)

In [29]:
# number of element in a series
ser.size

3

In [30]:
len(ser)

3

## **DataFrame attributes**

In [31]:
index = pd.Index(['John', 'Doe'], name="person")
df = pd.DataFrame([
    [24, 183, "black"],
    [42, 163, "blue"]
], index=index, columns=["Age", "Height_cm", "favorite_color"])

df

        Age  Height_cm favorite_color
person
John     24        183          black
Doe      42        163           blue

In [34]:
df.dtypes

Age                int64
Height_cm          int64
favorite_color    object
dtype: object

In [35]:
df.index

Index(['John', 'Doe'], dtype='object', name='person')

In [36]:
df.columns

Index(['Age', 'Height_cm', 'favorite_color'], dtype='object')

In [37]:
df.shape

(2, 3)

In [38]:
df.size

6

In [39]:
len(df) # Show the number of rows

2

# **Selection and Assignment**

## **Basic selection from a Series**

In [40]:
ser = pd.Series(list("abc") * 3)

ser

0    a
1    b
2    c
3    a
4    b
5    c
6    a
7    b
8    c
dtype: object

In [44]:
# selecting by row label
ser[3]

'a'

In [48]:
ser[[3]]

3    a
dtype: object

In [49]:
# selecting multiple element
ser[[0, 2]]

0    a
2    c
dtype: object

In [51]:
ser[:3]

0    a
1    b
2    c
dtype: object

In [59]:
# selecting the four last element
ser[-4:]

5    c
6    a
7    b
8    c
dtype: object

In [60]:
ser[2:6]

2    c
3    a
4    b
5    c
dtype: object

In [61]:
ser[1:8:3]

1    b
4    b
7    b
dtype: object

In [63]:
ser = pd.Series(range(3), index=['John', 'Doe', 'Jill'])
ser

John    0
Doe     1
Jill    2
dtype: int64

In [65]:
ser['John']

np.int64(0)

In [66]:
ser[['John']]

John    0
dtype: int64

In [67]:
ser = pd.Series(range(3), index=[2, 42, 64])

ser

2     0
42    1
64    2
dtype: int64

In [72]:
ser[2] # integer argument indecate raw index not raw position

np.int64(0)

In [75]:
ser[:2] # slicing still work positionaly

0     apple
1    banana
dtype: object

In [74]:
ser = pd.Series(["apple", "banana", "orange"], index=[0, 1, 1])

ser

0     apple
1    banana
1    orange
dtype: object

In [76]:
ser[1]

1    banana
1    orange
dtype: object

## **Basic selection from a DataFrame**

In [77]:
df = pd.DataFrame(np.arange(9).reshape(3, -1), columns=["a", "b", "c"])

df

   a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [79]:
df["a"]

0    0
1    3
2    6
Name: a, dtype: int64

In [80]:
df[["a"]]

   a
0  0
1  3
2  6

In [81]:
df[["a", "b"]]

   a  b
0  0  1
1  3  4
2  6  7

In [84]:
df[:2] # selecting by row index

   a  b  c
0  0  1  2
1  3  4  5

In [86]:
df[["a", "b"]]

   a  b
0  0  1
1  3  4
2  6  7

In [88]:
df[["b", "a"]] # reorder columns

   b  a
0  1  0
1  4  3
2  7  6

## **Position-based selection of a Series**

In [89]:
ser = pd.Series(["apple", "banana", "orange"], index=[0, 1, 1])

ser

0     apple
1    banana
1    orange
dtype: object

In [90]:
ser.iloc[1]

'banana'

In [91]:
ser.iloc[[1]]

1    banana
dtype: object

In [93]:
ser.iloc[[2, 0]]

1    orange
0     apple
dtype: object

In [94]:
ser.iloc[:2]

0     apple
1    banana
dtype: object

## **Position-based selection of a DataFrame**

In [97]:
df = pd.DataFrame(np.arange(20).reshape(5, -1), columns=list("abcd"))

df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [98]:
df.iloc[2, 2]

np.int64(10)

In [103]:
df.iloc[:, 0]

0     0
1     4
2     8
3    12
4    16
Name: a, dtype: int64

In [104]:
df.iloc[0, :]

a    0
b    1
c    2
d    3
Name: 0, dtype: int64

In [105]:
df.iloc[:, [0]] # return a DataFrame rather than a Serie

    a
0   0
1   4
2   8
3  12
4  16

In [106]:
df.iloc[[0], :]

   a  b  c  d
0  0  1  2  3

In [107]:
df.iloc[[0, 1], [-4, -1]]

   a  d
0  0  3
1  4  7

## **Label-based selection from a Series**

In [108]:
ser = pd.Series(["apple", "banana", "orange"], index=[0, 1, 1])

ser

0     apple
1    banana
1    orange
dtype: object

In [109]:
ser.loc[1]

1    banana
1    orange
dtype: object

In [111]:
ser = pd.Series([4, 4, 2], index=["cat", "dog", 'fish'], name='num_legs')

ser

cat     4
dog     4
fish    2
Name: num_legs, dtype: int64

In [112]:
ser.loc["dog"]

np.int64(4)

In [113]:
ser.loc[["dog"]]

dog    4
Name: num_legs, dtype: int64

In [114]:
ser.loc[["dog", "cat"]]

dog    4
cat    4
Name: num_legs, dtype: int64

In [115]:
ser.loc[:"fish"]

cat     4
dog     4
fish    2
Name: num_legs, dtype: int64

In [116]:
name = ["Jack", "Jill", "Jayn"]
ser = pd.Series(name)

ser

0    Jack
1    Jill
2    Jayn
dtype: object

In [117]:
name[:2]

['Jack', 'Jill']

In [118]:
ser.iloc[:2]

0    Jack
1    Jill
dtype: object

In [121]:
ser.loc[:2] # produce a different behavior

0    Jack
1    Jill
2    Jayn
dtype: object

In [122]:
ser1 = pd.Series(range(5), index=[0, 1, 2, 2, 3])

ser1

0    0
1    1
2    2
2    3
3    4
dtype: int64

In [123]:
ser1.loc[:2]

0    0
1    1
2    2
2    3
dtype: int64

In [124]:
ser = pd.Series(range(4), index=["zzz", "xxx", "xxx", "yyy"])

ser

zzz    0
xxx    1
xxx    2
yyy    3
dtype: int64

In [125]:
ser.loc["xxx"]

xxx    1
xxx    2
dtype: int64

In [126]:
ser = pd.Series(range(4), index=["zzz", "xxx", "yyy", "xxx"])

ser

zzz    0
xxx    1
yyy    2
xxx    3
dtype: int64

In [128]:
# ser.loc[:"xxx"] => KeyError: "Cannot get right slice bound for non-unique label: 'xxx'"

## **Label-based selection from a DataFrame**

In [129]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=["Age", "Height_cm", "eye_color"], index=["Jack", "Jill", "Jayne"])

df

       Age  Height_cm eye_color
Jack    24        180      blue
Jill    42        166     brown
Jayne   22        160     green

In [131]:
df.loc["Jayne", "eye_color"]

'green'

In [132]:
df.loc["Jayne", ["eye_color"]]

eye_color    green
Name: Jayne, dtype: object

In [133]:
df.loc[["Jayne"], ["eye_color"]]

      eye_color
Jayne     green

In [135]:
df.loc[:, "Age"]

Jack     24
Jill     42
Jayne    22
Name: Age, dtype: int64

In [136]:
df.loc[:, ["Age"]]

       Age
Jack    24
Jill    42
Jayne   22

In [137]:
df.loc["Jack", :]

Age            24
Height_cm     180
eye_color    blue
Name: Jack, dtype: object

In [138]:
df.loc[:, ["Age"]]

       Age
Jack    24
Jill    42
Jayne   22

In [139]:
df.loc[["Jill"], :]

      Age  Height_cm eye_color
Jill   42        166     brown

In [142]:
df.loc[["Jack", "Jayne"], ["Age", "Height_cm"]]

       Age  Height_cm
Jack    24        180
Jayne   22        160

## **Mixing position-based and label-based selection**

In [143]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=["age", "height_cm", "eye_color"])

df

   age  height_cm eye_color
0   24        180      blue
1   42        166     brown
2   22        160     green

In [144]:
col_index = df.columns.get_indexer(["age", "eye_color"]) # get position index from list of label

col_index

array([0, 2])

In [145]:
df.iloc[[0, 1], col_index]

   age eye_color
0   24      blue
1   42     brown

In [146]:
df[["age", "eye_color"]].iloc[[0, 1]]

   age eye_color
0   24      blue
1   42     brown

In [147]:
import timeit

In [148]:
def get_indexer_approach():
    col_index = df.columns.get_indexer(["age", "eye_color"])
    df.iloc[[0, 1], col_index]

In [149]:
timeit.timeit(get_indexer_approach, number=10_000)

3.875960916000622

In [150]:
two_step_approach = lambda: df[["age", "eye_color"]].iloc[[0, 1]]

In [151]:
timeit.timeit(two_step_approach, number=10_000)

4.187814346998493

## **DataFrame.filter**

In [152]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=[
    "age",
    "height_cm",
    "eye_color"
], index=["Jack", "Jill", "Jayne"])

df

       age  height_cm eye_color
Jack    24        180      blue
Jill    42        166     brown
Jayne   22        160     green

In [154]:
df.filter(["age", "eye_color"]) # select columns matching the label argument

       age eye_color
Jack    24      blue
Jill    42     brown
Jayne   22     green

In [155]:
df.filter(["Jack", "Jill"], axis=0)

      age  height_cm eye_color
Jack   24        180      blue
Jill   42        166     brown

In [156]:
df.filter(like="_")

       height_cm eye_color
Jack         180      blue
Jill         166     brown
Jayne        160     green

In [157]:
df.filter(regex=r"^Ja.*(?<!e)$", axis=0)

      age  height_cm eye_color
Jack   24        180      blue

## **Selection by data type**

In [2]:
df = pd.DataFrame([
    [0, 1.0, "2"],
    [4, 8.0, "16"]
], columns=["int_col", "float_col", "string"])

df

   int_col  float_col string
0        0        1.0      2
1        4        8.0     16

In [3]:
df.select_dtypes("int")

   int_col
0        0
1        4

In [5]:
df.select_dtypes(np.int64)

   int_col
0        0
1        4

In [6]:
df.select_dtypes(include=["int", "float"])

   int_col  float_col
0        0        1.0
1        4        8.0

In [7]:
df.select_dtypes(exclude=["int", "float"])

  string
0      2
1     16

## **Selection/filtering via Boolean arrays**

In [13]:
mask = [True, False, True]
ser = pd.Series(range(3))

ser

0    0
1    1
2    2
dtype: int64

In [14]:
ser[mask]

0    0
2    2
dtype: int64

In [15]:
ser.loc[mask]

0    0
2    2
dtype: int64

In [16]:
df = pd.DataFrame(np.arange(6).reshape(3, -1))

df[mask]

   0  1
0  0  1
2  4  5

In [18]:
col_mask = [True, False]

df.iloc[mask, col_mask]

   0
0  0
2  4

In [19]:
df = pd.DataFrame([
    [24, 180, "blue"],
    [42, 166, "brown"],
    [22, 160, "green"],
], columns=["age", "height_cm", "eye_color"], index=["Jack", "Jill", "Jayne"])

df

       age  height_cm eye_color
Jack    24        180      blue
Jill    42        166     brown
Jayne   22        160     green

In [21]:
blue_eyes = df["eye_color"] == "blue"

blue_eyes

Jack      True
Jill     False
Jayne    False
Name: eye_color, dtype: bool

In [22]:
green_eyes = df["eye_color"] == "green"

green_eyes

Jack     False
Jill     False
Jayne     True
Name: eye_color, dtype: bool

In [23]:
mask = blue_eyes | green_eyes

mask

Jack      True
Jill     False
Jayne     True
Name: eye_color, dtype: bool

In [24]:
df[mask]

       age  height_cm eye_color
Jack    24        180      blue
Jayne   22        160     green

In [25]:
age_lt_age = df["age"] < 40

age_lt_age

Jack      True
Jill     False
Jayne     True
Name: age, dtype: bool

In [26]:
height_gt_170 = df["height_cm"] > 170

height_gt_170

Jack      True
Jill     False
Jayne    False
Name: height_cm, dtype: bool

In [27]:
df[age_lt_age & height_gt_170]

      age  height_cm eye_color
Jack   24        180      blue

In [28]:
df[~(age_lt_age & height_gt_170)]

       age  height_cm eye_color
Jill    42        166     brown
Jayne   22        160     green

## **Selection with a MultiIndex – A single level**

In [29]:
index = pd.MultiIndex.from_tuples([
    ("John", "Smith"),
    ("John", "Doe"),
    ("Jane", "Doe"),
    ("Stephen", "Smith"),
], names=["first_name", "last_name"])
ser = pd.Series(range(4), index=index)

ser

first_name  last_name
John        Smith        0
            Doe          1
Jane        Doe          2
Stephen     Smith        3
dtype: int64

In [33]:
ser.loc["John"] # Pandas try to Reduce the Multiple Index level (first level)

last_name
Smith    0
Doe      1
dtype: int64

In [34]:
ser.loc[["John"]]

first_name  last_name
John        Smith        0
            Doe          1
dtype: int64

## **Selection with a MultiIndex – Multiple levels**

In [35]:
index = pd.MultiIndex.from_tuples([
    ("John", "Smith"),
    ("John", "Doe"),
    ("Jane", "Doe"),
    ("Stephen", "Smith"),
], names=["first_name", "last_name"])
ser = pd.Series(range(4), index=index)

ser

first_name  last_name
John        Smith        0
            Doe          1
Jane        Doe          2
Stephen     Smith        3
dtype: int64

In [36]:
ser.loc[("Jane", "Doe")]

np.int64(2)

In [37]:
ser.loc[[("Jane", "Doe")]]

first_name  last_name
Jane        Doe          2
dtype: int64

In [38]:
ser.loc[(["Jane"], "Doe")]

first_name  last_name
Jane        Doe          2
dtype: int64

In [40]:
ser.loc[[("John", "Smith"), ("Jane","Doe")]]

first_name  last_name
John        Smith        0
Jane        Doe          2
dtype: int64

In [41]:
ser.loc[(slice(None), "Doe")]

first_name
John    1
Jane    2
dtype: int64

In [43]:
ser.loc[([slice(None)], "Doe")]

first_name  last_name
John        Doe          1
Jane        Doe          2
dtype: int64

In [44]:
ser.loc[([slice(None)], ["Doe"])]

first_name  last_name
John        Doe          1
Jane        Doe          2
dtype: int64

In [45]:
alist = list("abc")

alist[:]

['a', 'b', 'c']

In [47]:
alist[slice(None)] # Create a empty slice without no start or stop value

['a', 'b', 'c']

In [48]:
ser.loc[([slice(None)], ["Doe"])]

first_name  last_name
John        Doe          1
Jane        Doe          2
dtype: int64

In [49]:
ixsl = pd.IndexSlice
ser.loc[ixsl[:, ["Doe"]]]

first_name  last_name
John        Doe          1
Jane        Doe          2
dtype: int64

## **Selection with a MultiIndex – a DataFrame**

In [2]:
row_index = pd.MultiIndex.from_tuples([
    ("John", "Smith"),
    ("John", "Doe"),("Jane", "Doe"),
    ("Stephen", "Smith"),
], names=["first_name", "last_name"])

row_index

MultiIndex([(   'John', 'Smith'),
            (   'John',   'Doe'),
            (   'Jane',   'Doe'),
            ('Stephen', 'Smith')],
           names=['first_name', 'last_name'])

In [3]:
col_index = pd.MultiIndex.from_tuples([
    ("music", "favorite"),
    ("music", "last_seen_live"),
    ("art", "favorite"),
], names=["art_type", "category"])

col_index

MultiIndex([('music',       'favorite'),
            ('music', 'last_seen_live'),
            (  'art',       'favorite')],
           names=['art_type', 'category'])

In [4]:
df = pd.DataFrame([
    ["Swift", "Swift", "Matisse"],
    ["Mozart", "T. Swift", "Van Gogh"],
    ["Beatles", "Wonder", "Warhol"],
    ["Jackson", "Dylan", "Picasso"],
], index=row_index, columns=col_index)

df

art_type                music                      art
category             favorite last_seen_live  favorite
first_name last_name
John       Smith        Swift          Swift   Matisse
           Doe         Mozart       T. Swift  Van Gogh
Jane       Doe        Beatles         Wonder    Warhol
Stephen    Smith      Jackson          Dylan   Picasso

In [5]:
row_index = (slice(None), "Smith")
col_index = (slice(None), "favorite")

df.loc[row_index, col_index]

art_type                music      art
category             favorite favorite
first_name last_name
John       Smith        Swift  Matisse
Stephen    Smith      Jackson  Picasso

In [6]:
df.loc[(slice(None), "Smith"), (slice(None), "favorite")]

art_type                music      art
category             favorite favorite
first_name last_name
John       Smith        Swift  Matisse
Stephen    Smith      Jackson  Picasso

## **Item assignment with `.loc` and `.iloc`**

> **The pandas library is optimized for reading, exploring, and evaluating data. Operations that try to mutate or change data are far less efficient.**

In [7]:
ser = pd.Series(range(3), index=list("abc"))

ser

a    0
b    1
c    2
dtype: int64

In [9]:
ser.loc["b"] = 42

ser

a     0
b    42
c     2
dtype: int64

In [11]:
ser.iloc[2] = -42

ser

a     0
b    42
c   -42
dtype: int64

- The cost of mutating data through pandas can depend largely on two factors:
    - The type of array backing a pandas pd.Series (Chapter 3, Data Types, will cover data types in more detail)
    - How many objects reference a pd.Series
- A deep dive into those factors is far beyond the scope of this book. For the first point above, my general guidance is that the simpler an array type is, the better your odds are of being able to mutate it without the array contents having to be copied, which for larger datasets may be prohibitively expensive.
- For the second bullet, a lot of **`Copy on Write (CoW)`** work was involved in the pandas 2.x series. CoW is the default behavior in pandas 3.0, and it tries to make the behavior of what does and does not get copied when mutating data more predictable. For advanced users, I highly encourage giving the pandas **`CoW`** documentation a read

## **DataFrame column assignment**

In [16]:
df = pd.DataFrame({"col1": [1, 2, 3]})

df

   col1
0     1
1     2
2     3

In [17]:
df["new_column1"] = 42

df

   col1  new_column1
0     1           42
1     2           42
2     3           42

In [19]:
df["new_column2"] = list("abc")

df

   col1  new_column1 new_column2
0     1           42           a
1     2           42           b
2     3           42           c

In [20]:
df["new_column3"] = pd.Series(["dog", "cat", "human"])

df

   col1  new_column1 new_column2 new_column3
0     1           42           a         dog
1     2           42           b         cat
2     3           42           c       human

In [21]:
row_index = pd.MultiIndex.from_tuples([
    ("John", "Smith"),
    ("John", "Doe"),
    ("Jane", "Doe"),
    ("Stephen", "Smith"),
], names=["first_name", "last_name"])

col_index = pd.MultiIndex.from_tuples([
    ("music", "favorite"),
    ("music", "last_seen_live"),
    ("art", "favorite"),
], names=["art_type", "category"])

df = pd.DataFrame([
    ["Swift", "Swift", "Matisse"],
    ["Mozart", "T. Swift", "Van Gogh"],
    ["Beatles", "Wonder", "Warhol"],
    ["Jackson", "Dylan", "Picasso"],
], index=row_index, columns=col_index)

df

art_type                music                      art
category             favorite last_seen_live  favorite
first_name last_name
John       Smith        Swift          Swift   Matisse
           Doe         Mozart       T. Swift  Van Gogh
Jane       Doe        Beatles         Wonder    Warhol
Stephen    Smith      Jackson          Dylan   Picasso

In [22]:
df.loc[:, ("art", "museuems_seen")] = [1, 2, 4, 8]

df

art_type                music                      art
category             favorite last_seen_live  favorite museuems_seen
first_name last_name
John       Smith        Swift          Swift   Matisse             1
           Doe         Mozart       T. Swift  Van Gogh             2
Jane       Doe        Beatles         Wonder    Warhol             4
Stephen    Smith      Jackson          Dylan   Picasso             8

In [23]:
df = pd.DataFrame([[0, 1], [2, 4]], columns=list("ab"))

df

   a  b
0  0  1
1  2  4

In [24]:
(
    df
    .mul(2)
    .add(42)
)

    a   b
0  42  44
1  46  50

In [25]:
df2 = (
    df
    .mul(2)
    .add(42)
)

df2["assigned_c"] = df2["b"] - 3

df2

    a   b  assigned_c
0  42  44          41
1  46  50          47

In [26]:
(
    df
    .mul(2)
    .add(42)
    .assign(
        assigned_c = lambda x: x["b"] - 3
    )
)

    a   b  assigned_c
0  42  44          41
1  46  50          47

# **Data Types**

## **Integral types**

In [30]:
pd.Series(range(3), dtype=pd.Int64Dtype())

0    0
1    1
2    2
dtype: Int64

In [31]:
pd.Series(range(3), dtype=pd.Int8Dtype())

0    0
1    1
2    2
dtype: Int8

In [32]:
pd.Series([1, pd.NA, 2], dtype=pd.Int8Dtype())

0       1
1    <NA>
2       2
dtype: Int8

In [33]:
pd.Series([1, None, 2], dtype=pd.Int8Dtype()) # pandas convert None Value into pd.NA

0       1
1    <NA>
2       2
dtype: Int8

![Integral limits per signedness and width](../Images/Integral_limits_per_signedness_and_width.png)

In [34]:
pd.Series(range(555, 558), dtype=pd.Int16Dtype())

0    555
1    556
2    557
dtype: Int16

In [2]:
pd.Series(range(3), dtype=pd.UInt16Dtype())

0    0
1    1
2    2
dtype: UInt16

## **Floating point types**

In [3]:
pd.Series([3.14, .333333333, -123.456], dtype=pd.Float64Dtype())

0        3.14
1    0.333333
2    -123.456
dtype: Float64

In [4]:
pd.Series([3.14, None, pd.NA], dtype=pd.Float64Dtype())

0    3.14
1    <NA>
2    <NA>
dtype: Float64

In [9]:
ser1 = pd.Series([1_000_000.123], dtype=pd.Float32Dtype())
ser2 = pd.Series([1_000_000.123], dtype=pd.Float32Dtype())

ser1.eq(ser2)

0    True
dtype: boolean

In [10]:
ser1.equals(ser2)

True

## **Boolean types**

In [14]:
ser1 = pd.Series([True, False, True], dtype=pd.BooleanDtype())

ser1

0     True
1    False
2     True
dtype: boolean

In [15]:
ser2 = pd.Series([1, 0, 1], dtype=pd.BooleanDtype())

ser2

0     True
1    False
2     True
dtype: boolean

In [26]:
ser1.eq(ser2)

0    True
1    True
2    True
dtype: boolean

In [23]:
ser1.equals(ser2)

True

In [27]:
pd.Series([1, pd.NA, None], dtype=pd.BooleanDtype())

0    True
1    <NA>
2    <NA>
dtype: boolean

## **String types**

In [28]:
pd.Series(["foo", "bar", "baz"], dtype=pd.StringDtype())

0    foo
1    bar
2    baz
dtype: string

In [29]:
pd.Series(["foo", pd.NA, None], dtype=pd.StringDtype())

0     foo
1    <NA>
2    <NA>
dtype: string

In [30]:
ser = pd.Series(["xx", "YyY", "zZzZ"], dtype=pd.StringDtype())

ser.str.len()

0    2
1    3
2    4
dtype: Int64

In [31]:
ser.str.upper()

0      XX
1     YYY
2    ZZZZ
dtype: string

In [32]:
ser.str.lower()

0      xx
1     yyy
2    zzzz
dtype: string

In [33]:
ser.str.title()

0      Xx
1     Yyy
2    Zzzz
dtype: string

In [34]:
ser = pd.Series(["foo", "bar", "baz"], dtype=pd.StringDtype())

ser.str.contains("o")

0     True
1    False
2    False
dtype: boolean

In [38]:
ser.str.contains(r"^ba[rz]$", case=False, regex=True)

0    False
1     True
2     True
dtype: boolean

## **Missing value handling**

In [39]:
ser = pd.Series(range(3))

ser

0    0
1    1
2    2
dtype: int64

In [40]:
ser.iloc[1] = None

ser

0    0.0
1    NaN
2    2.0
dtype: float64

In [42]:
pd.isna(pd.Series([1, np.nan, 2]))

0    False
1     True
2    False
dtype: bool

In [45]:
pd.isna(pd.Series([1, pd.NA, 2], dtype=pd.Int64Dtype()))

0    False
1     True
2    False
dtype: bool

In [49]:
ser = pd.Series(range(3), dtype=pd.Int64Dtype())
mask = pd.Series([True, pd.NA, False], dtype=pd.BooleanDtype())

mask

0     True
1     <NA>
2    False
dtype: boolean

In [50]:
ser[mask]

0    0
dtype: Int64

In [51]:
mask = pd.Series([True, None, False])
# ser[mask] => alueError: Cannot mask with non-boolean array containing NA / NaN values

In [63]:
mask = pd.Series([True, None, False])
mask = mask.fillna(False).astype(bool)

ser[mask]

/tmp/ipykernel_4808/4023848777.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  mask = mask.fillna(False).astype(bool)

0    0
dtype: Int64

## **Categorical types**

In [64]:
values = ["foo", "bar", "baz"]
values_ser = pd.Series(values, dtype=pd.StringDtype())

values_ser

0    foo
1    bar
2    baz
dtype: string

In [65]:
ser = values_ser.astype(pd.CategoricalDtype())

ser

0    foo
1    bar
2    baz
dtype: category
Categories (3, string): [bar, baz, foo]

In [66]:
cat = pd.CategoricalDtype(values_ser)

cat

CategoricalDtype(categories=['foo', 'bar', 'baz'], ordered=False, categories_dtype=string)

In [67]:
ser = pd.Series(values, dtype=cat)

ser

0    foo
1    bar
2    baz
dtype: category
Categories (3, string): [foo, bar, baz]

In [68]:
ser.iloc[2] = "foo"

ser

0    foo
1    bar
2    foo
dtype: category
Categories (3, string): [foo, bar, baz]

In [70]:
# ser.iloc[2] = "qux" TypeError: Cannot setitem on a Categorical with a new category (qux), set the categories first

In [74]:
shirt_sizes = pd.Series(["S", "M", "L", "XL"], dtype=pd.StringDtype())
cat = pd.CategoricalDtype(shirt_sizes, ordered=True)
ser = pd.Series(["XL", "L", "S", "L", "S", "M"], dtype=cat)

ser

0    XL
1     L
2     S
3     L
4     S
5     M
dtype: category
Categories (4, string): [S < M < L < XL]

In [75]:
ser < "L"

0    False
1    False
2     True
3    False
4     True
5     True
dtype: bool

In [77]:
accepted_values = pd.Series(["foo", "bar"], dtype=pd.StringDtype())
cat = pd.CategoricalDtype(accepted_values)
ser = pd.Series(["foo", "bar", "foo"], dtype=cat)

ser

0    foo
1    bar
2    foo
dtype: category
Categories (2, string): [foo, bar]

In [79]:
ser.cat.codes

0    0
1    1
2    0
dtype: int8

In [80]:
ser.cat.categories

Index(['foo', 'bar'], dtype='string')

In [84]:
pd.Series(["foo", "bar", "baz"] * 100, dtype=pd.StringDtype()).memory_usage()

2532

In [83]:
pd.Series(["foo", "bar", "baz"] * 100, dtype=cat).memory_usage()

556

In [85]:
pd.Series(["foo", "bar", pd.NA], dtype=pd.CategoricalDtype())

0    foo
1    bar
2    NaN
dtype: category
Categories (2, object): ['bar', 'foo']

In [86]:
values = pd.Series(["foo", "bar"], dtype=pd.StringDtype())
cat = pd.CategoricalDtype(values)

pd.Series(["foo", "bar", pd.NA], dtype=cat)

0     foo
1     bar
2    <NA>
dtype: category
Categories (2, string): [foo, bar]

> **check PDEP-16**

## **Temporal types – datetime**

In [87]:
ser = pd.Series([
    "2024-01-01 00:00:00",
    "2024-01-02 00:00:01",
    "2024-01-03 00:00:02"
], dtype="datetime64[ns]")

ser

0   2024-01-01 00:00:00
1   2024-01-02 00:00:01
2   2024-01-03 00:00:02
dtype: datetime64[ns]

In [89]:
ser = pd.Series([
    "2024-01-01",
    "2024-01-02",
    "2024-01-03"
], dtype="datetime64[ns]")

ser

0   2024-01-01
1   2024-01-02
2   2024-01-03
dtype: datetime64[ns]

In [90]:
ser.iloc[1] = "2024-01-04 00:00:42"

ser

0   2024-01-01 00:00:00
1   2024-01-04 00:00:42
2   2024-01-03 00:00:00
dtype: datetime64[ns]

In [91]:
ser.dt.year

0    2024
1    2024
2    2024
dtype: int32

In [92]:
ser.dt.month

0    1
1    1
2    1
dtype: int32

In [93]:
ser.dt.day

0    1
1    4
2    3
dtype: int32

In [94]:
ser.dt.day_of_week

0    0
1    3
2    2
dtype: int32

In [95]:
pd.Series([
    "2024-01-01 00:00:01",
    "2024-01-02 00:00:01",
    "2024-01-03 00:00:01"
], dtype=pd.DatetimeTZDtype(tz="UTC"))

0   2024-01-01 00:00:01+00:00
1   2024-01-02 00:00:01+00:00
2   2024-01-03 00:00:01+00:00
dtype: datetime64[ns, UTC]

In [96]:
pd.Series([
    "2024-01-01 00:00:01",
    "2024-01-02 00:00:01",
    "2024-01-03 00:00:01"
], dtype=pd.DatetimeTZDtype(tz="America/New_York"))

0   2024-01-01 00:00:01-05:00
1   2024-01-02 00:00:01-05:00
2   2024-01-03 00:00:01-05:00
dtype: datetime64[ns, America/New_York]

In [97]:
pd.Series([
    "2024-01-01 00:00:01",
    "2024-01-02 00:00:01",
    "2024-01-03 00:00:01"
], dtype=pd.DatetimeTZDtype(tz="-05:00"))

0   2024-01-01 00:00:01-05:00
1   2024-01-02 00:00:01-05:00
2   2024-01-03 00:00:01-05:00
dtype: datetime64[ns, UTC-05:00]

In [98]:
ser_no_tz = pd.Series([
    "2024-01-01 00:00:00",
    "2024-01-01 00:01:10",
    "2024-01-01 00:02:42"
], dtype="datetime64[ns]")
ser_et = ser_no_tz.dt.tz_localize("America/New_York")

ser_et

0   2024-01-01 00:00:00-05:00
1   2024-01-01 00:01:10-05:00
2   2024-01-01 00:02:42-05:00
dtype: datetime64[ns, America/New_York]

In [99]:
ser_pt = ser_et.dt.tz_convert("America/Los_Angeles")

ser_pt

0   2023-12-31 21:00:00-08:00
1   2023-12-31 21:01:10-08:00
2   2023-12-31 21:02:42-08:00
dtype: datetime64[ns, America/Los_Angeles]

In [101]:
ser_pt.dt.normalize()

0   2023-12-31 00:00:00-08:00
1   2023-12-31 00:00:00-08:00
2   2023-12-31 00:00:00-08:00
dtype: datetime64[ns, America/Los_Angeles]

In [102]:
ser = pd.Series([
    "2024-01-01",
    None,
    "2024-01-03"
], dtype="datetime64[ns]")

ser

0   2024-01-01
1          NaT
2   2024-01-03
dtype: datetime64[ns]

In [103]:
ser.isna()

0    False
1     True
2    False
dtype: bool

In [104]:
ser.isnull()

0    False
1     True
2    False
dtype: bool

In [106]:
# pd.Series([
#     "1500-01-01 00:00:01",
#     "2500-01-01 00:00:01",
# ], dtype="datetime64[ns]") => OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1500-01-01 00:00:01, at position 0

In [107]:
pd.Series([
    "1500-01-01 00:00:01",
    "2500-01-01 00:00:01",
], dtype="datetime64[us]")

0   1500-01-01 00:00:01
1   2500-01-01 00:00:01
dtype: datetime64[us]

## **Temporal types – timedelta**

In [108]:
ser = pd.Series([
    "2024-01-01",
    "2024-01-02",
    "2024-01-03"
], dtype="datetime64[ns]")

ser - pd.Timestamp("2023-12-31 12:00:00")

0   0 days 12:00:00
1   1 days 12:00:00
2   2 days 12:00:00
dtype: timedelta64[ns]

In [109]:
ser + pd.Timedelta("3 days")

0   2024-01-04
1   2024-01-05
2   2024-01-06
dtype: datetime64[ns]

In [111]:
pd.Series([
    "-1 days",
    "6 hours",
    "42 minutes",
    "12 seconds",
    "8 milliseconds",
    "4 microseconds",
    "300 nanoseconds",
], dtype="timedelta64[ns]")

0           -1 days +00:00:00
1             0 days 06:00:00
2             0 days 00:42:00
3             0 days 00:00:12
4      0 days 00:00:00.008000
5      0 days 00:00:00.000004
6   0 days 00:00:00.000000300
dtype: timedelta64[ns]

In [113]:
# pd.Series([
#     "1 months",
# ], dtype="timedelta64[ns]") => ValueError: invalid unit abbreviation: months

## **Temporal PyArrow types**

In [115]:
ser = pd.Series([
    "2024-01-01",
    "2024-01-02",
    "2024-01-03",
], dtype=pd.ArrowDtype(pa.date32()))

ser

0    2024-01-01
1    2024-01-02
2    2024-01-03
dtype: date32[day][pyarrow]

In [116]:
ser = pd.Series([
    "9999-12-29",
    "9999-12-30",
    "9999-12-31",
], dtype=pd.ArrowDtype(pa.date32()))

ser

0    9999-12-29
1    9999-12-30
2    9999-12-31
dtype: date32[day][pyarrow]

## **PyArrow List types**

In [117]:
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Janice", "Jim", "Michael"],
    "years_exp": [10, 2, 4, 8, 6],
})

df

      name  years_exp
0    Alice         10
1      Bob          2
2   Janice          4
3      Jim          8
4  Michael          6

In [118]:
ser = pd.Series([
    ["Bob", "Michael"],
    None,
    None,
    ["Janice"],
    None,
], dtype=pd.ArrowDtype(pa.list_(pa.string())))

ser

0    ['Bob' 'Michael']
1                 <NA>
2                 <NA>
3           ['Janice']
4                 <NA>
dtype: list<item: string>[pyarrow]

In [119]:
df["direct_reports"] = ser

df

      name  years_exp     direct_reports
0    Alice         10  ['Bob' 'Michael']
1      Bob          2               <NA>
2   Janice          4               <NA>
3      Jim          8         ['Janice']
4  Michael          6               <NA>

In [120]:
ser.list.len()

0       2
1    <NA>
2    <NA>
3       1
4    <NA>
dtype: int32[pyarrow]

In [121]:
ser.list[0]

0       Bob
1      <NA>
2      <NA>
3    Janice
4      <NA>
dtype: string[pyarrow]

In [122]:
ser.list.flatten()

0        Bob
1    Michael
2     Janice
dtype: string[pyarrow]

## **PyArrow decimal types**

In [123]:
pd.Series([
    "123456789.123456789",
    "-987654321.987654321",
    "99999999.9999999999",
], dtype=pd.ArrowDtype(pa.decimal128(19, 10)))

0     123456789.1234567890
1    -987654321.9876543210
2      99999999.9999999999
dtype: decimal128(19, 10)[pyarrow]

In [124]:
pd.Series([
    123456789.123456789,
    -987654321.987654321,
    99999999.9999999999,
], dtype=pd.ArrowDtype(pa.decimal128(19, 10)))

0     123456789.1234567910
1    -987654321.9876543283
2     100000000.0000000000
dtype: decimal128(19, 10)[pyarrow]

> Pay special attention to the fact that we provided our data as **strings**. If we had tried to provide that as **floating point** data to begin with, we would have immediately seen a loss in precision

In [125]:
99999999.9999999999 == 100000000.0

True

In [126]:
import decimal

In [128]:
decimal.Decimal("99999999.9999999999") == decimal.Decimal("100000000.0")

False

In [129]:
decimal.Decimal("99999999.9999999999") + decimal.Decimal("100000000.0")

Decimal('199999999.9999999999')

In [130]:
pd.Series([
    decimal.Decimal("123456789.123456789"),
    decimal.Decimal("-987654321.987654321"),
    decimal.Decimal("99999999.9999999999"),
], dtype=pd.ArrowDtype(pa.decimal128(19, 10)))

0     123456789.1234567890
1    -987654321.9876543210
2      99999999.9999999999
dtype: decimal128(19, 10)[pyarrow]

> The **`pa.decimal128`** data type can only support up to 38 significant decimal digits.

In [131]:
ser = pd.Series([
    "123456789123456789123456789123456789.123456789"
], dtype=pd.ArrowDtype(pa.decimal256(76, 10)))

ser

0    123456789123456789123456789123456789.1234567890
dtype: decimal256(76, 10)[pyarrow]

## **NumPy type system, the object type, and pitfalls**

In [132]:
pd.Series([0, 1, 2])

0    0
1    1
2    2
dtype: int64

In [133]:
pd.Series([0, None, 2])

0    0.0
1    NaN
2    2.0
dtype: float64

In [135]:
# pd.Series([0, None, 2], dtype=int) => TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [136]:
ser = pd.Series([0, None, 2])

ser.fillna(0).astype(int)

0    0
1    0
2    2
dtype: int64

In [137]:
pd.Series([0, None, 2]).fillna(0).astype(int).mean()

np.float64(0.6666666666666666)

In [138]:
pd.Series([0, None, 2], dtype=pd.Int64Dtype()).mean()

np.float64(1.0)

In [139]:
import timeit

In [140]:
func = lambda: pd.Series([0, None, 2]).fillna(0).astype(int).mean()
timeit.timeit(func, number=10_000)

2.171371218000786

In [141]:
func = lambda: pd.Series([0, None, 2], dtype=pd.Int64Dtype())
timeit.timeit(func, number=10_000)

0.8741634490015713

In [142]:
pd.Series([True, False])

0     True
1    False
dtype: bool

In [143]:
pd.Series([True, False, None])

0     True
1    False
2     None
dtype: object

In [145]:
pd.Series([True, False, None, "one of these things", ["is not like"], ["the others"]])

0                   True
1                  False
2                   None
3    one of these things
4          [is not like]
5           [the others]
dtype: object

In [146]:
pd.Series([True, False, None], dtype=pd.BooleanDtype())

0     True
1    False
2     <NA>
dtype: boolean

In [148]:
pd.Series(["foo", "bar", "baz"])

0    foo
1    bar
2    baz
dtype: object

In [149]:
ser = pd.Series(["foo", "bar", "baz"])
ser.iloc[2] = 42

ser

0    foo
1    bar
2     42
dtype: object

In [151]:
# ser = pd.Series(["foo", "bar", "baz"], dtype=pd.StringDtype())
# ser.iloc[2] = 42 => TypeError: Invalid value '42' for dtype 'string'. Value should be a string or missing value, got 'int' instead.

In [152]:
alist = [42, "foo", ["sub", "list"], {"key": "value"}]
ser = pd.Series(alist)

ser

0                  42
1                 foo
2         [sub, list]
3    {'key': 'value'}
dtype: object

In [153]:
df = pd.DataFrame([
    ["foo", 1, 123.45],
    ["bar", 2, 333.33],
    ["baz", 3, 999.99],
], columns=list("abc"))

df

     a  b       c
0  foo  1  123.45
1  bar  2  333.33
2  baz  3  999.99

In [154]:
df.dtypes

a     object
b      int64
c    float64
dtype: object

In [155]:
df.astype({
    "a": pd.StringDtype(),
    "b": pd.Int64Dtype(),
    "c": pd.Float64Dtype(),
}).dtypes

a    string[python]
b             Int64
c           Float64
dtype: object

In [156]:
df.convert_dtypes(dtype_backend="numpy_nullable").dtypes

a    string[python]
b             Int64
c           Float64
dtype: object