In [1]:
import numpy as np
import pandas as pd

# **Basic pd.Series arithmetic**

In [2]:
ser = pd.Series(range(3), dtype=pd.Int64Dtype())

ser

0    0
1    1
2    2
dtype: Int64

In [3]:
ser + 42

0    42
1    43
2    44
dtype: Int64

In [5]:
ser - 42

0    -42
1    -41
2    -40
dtype: Int64

In [6]:
ser * 42

0     0
1    42
2    84
dtype: Int64

In [7]:
ser / 42

0         0.0
1     0.02381
2    0.047619
dtype: Float64

In [8]:
ser2 = pd.Series(range(10, 13), dtype=pd.Int64Dtype())

ser + ser2

0    10
1    12
2    14
dtype: Int64

In [9]:
ser1 = pd.Series([1., 2., 3.], dtype=pd.Float64Dtype())
ser2 = pd.Series([4., pd.NA, 6.], dtype=pd.Float64Dtype())

ser.add(ser2)

0     4.0
1    <NA>
2     8.0
dtype: Float64

In [10]:
ser1.add(ser2, fill_value=0)

0    5.0
1    2.0
2    9.0
dtype: Float64

In [11]:
ser1 = pd.Series(range(3), dtype=pd.Int64Dtype())
ser2 = pd.Series(range(3), dtype=pd.Int64Dtype())

ser1 + ser2

0    0
1    2
2    4
dtype: Int64

In [12]:
ser3 = pd.Series([2, 4], dtype=pd.Int64Dtype())

ser1 + ser3

0       2
1       5
2    <NA>
dtype: Int64

In [13]:
ser4 = pd.Series([2, 4, 8], index=[1, 2, 3], dtype=pd.Int64Dtype())

ser1 + ser4

0    <NA>
1       3
2       6
3    <NA>
dtype: Int64

In [14]:
ser5 = pd.Series([2, 4, 8], index=[0, 1, 1], dtype=pd.Int64Dtype())

ser1 + ser5

0       2
1       5
1       9
2    <NA>
dtype: Int64

In [15]:
import timeit

In [20]:
func = lambda: pd.Series(range(10000), dtype=pd.Int64Dtype()) + pd.Series(range(10000), dtype=pd.Int64Dtype())
timeit.timeit(func, number=10_000)

2.119075100000373

In [21]:
func = lambda: pd.Series(range(10_000), dtype=pd.Int64Dtype()).add(pd.Series(range(10_000), dtype=pd.Int64Dtype()))
timeit.timeit(func, number=10_000)

2.1072990929997104

# **Basic pd.DataFrame arithmetic**

In [22]:
np.random.seed(42)

df = pd.DataFrame(
    np.random.randn(3, 3),
    columns=["col1", "col2", "col3"],
    index=["row1", "row2", "row3"],
).convert_dtypes(dtype_backend="numpy_nullable")

df

          col1      col2      col3
row1  0.496714 -0.138264  0.647689
row2   1.52303 -0.234153 -0.234137
row3  1.579213  0.767435 -0.469474

In [23]:
df + 1

          col1      col2      col3
row1  1.496714  0.861736  1.647689
row2   2.52303  0.765847  0.765863
row3  2.579213  1.767435  0.530526

In [24]:
df * 2

          col1      col2      col3
row1  0.993428 -0.276529  1.295377
row2   3.04606 -0.468307 -0.468274
row3  3.158426  1.534869 -0.938949

In [25]:
ser = pd.Series(
    [20, 10, 0],
    index=["col1", "col2", "col3"],
    dtype=pd.Int64Dtype(),
)

ser

col1    20
col2    10
col3     0
dtype: Int64

In [26]:
df + ser

           col1       col2      col3
row1  20.496714   9.861736  0.647689
row2   21.52303   9.765847 -0.234137
row3  21.579213  10.767435 -0.469474

In [27]:
ser = pd.Series(
    [20, 10, 0, 42],
    index=["col1", "col2", "col3", "new_column"],
    dtype=pd.Int64Dtype(),
)

ser + df

           col1       col2      col3  new_column
row1  20.496714   9.861736  0.647689         NaN
row2   21.52303   9.765847 -0.234137         NaN
row3  21.579213  10.767435 -0.469474         NaN

In [28]:
ser = pd.Series(
    [20, 10, 0],
    index=["row1", "row2", "row3"],
    dtype=pd.Int64Dtype(),
)

ser

row1    20
row2    10
row3     0
dtype: Int64

In [29]:
df + ser

      col1  col2  col3  row1  row2  row3
row1  <NA>  <NA>  <NA>   NaN   NaN   NaN
row2  <NA>  <NA>  <NA>   NaN   NaN   NaN
row3  <NA>  <NA>  <NA>   NaN   NaN   NaN

In [30]:
ser = pd.Series(
    [20, 10, 0, 42],
    index=["row1", "row2", "row3", "row4"],
    dtype=pd.Int64Dtype(),
)

ser

row1    20
row2    10
row3     0
row4    42
dtype: Int64

In [31]:
df

          col1      col2      col3
row1  0.496714 -0.138264  0.647689
row2   1.52303 -0.234153 -0.234137
row3  1.579213  0.767435 -0.469474

In [32]:
df.add(ser, axis=0) # match up the row label

           col1       col2       col3
row1  20.496714  19.861736  20.647689
row2   11.52303   9.765847   9.765863
row3   1.579213   0.767435  -0.469474
row4       <NA>       <NA>       <NA>

In [33]:
df + df

          col1      col2      col3
row1  0.993428 -0.276529  1.295377
row2   3.04606 -0.468307 -0.468274
row3  3.158426  1.534869 -0.938949

In [35]:
np.random.seed(42)

df2 = pd.DataFrame(np.random.randn(3, 3)).convert_dtypes(dtype_backend="numpy_nullable")

df2

          0         1         2
0  0.496714 -0.138264  0.647689
1   1.52303 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474

In [36]:
df + df2

      col1  col2  col3     0     1     2
row1  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
row2  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
row3  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
0     <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1     <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
2     <NA>  <NA>  <NA>  <NA>  <NA>  <NA>

# **Aggregations**

In [37]:
np.random.seed(42)

ser = pd.Series(np.random.rand(10_000), dtype=pd.Float64Dtype())

In [38]:
print(f"Count is: {ser.count()}")
print(f"Mean value is: {ser.mean()}")
print(f"Standard deviation is: {ser.std()}")
print(f"Minimum value is: {ser.min()}")
print(f"Maximum value is: {ser.max()}")
print(f"Summation is: {ser.sum()}")

Count is: 10000
Mean value is: 0.49415955768429964
Standard deviation is: 0.28763012652699277
Minimum value is: 1.1634755366141114e-05
Maximum value is: 0.9997176732861306
Summation is: 4941.595576842997

In [46]:
# a Generic way
print(f"Count is: {ser.agg('count')}")
print(f"Mean value is: {ser.agg('mean')}")
print(f"Standard deviation is: {ser.agg('std')}")
print(f"Minimum value is: {ser.agg('min')}")
print(f"Maximum value is: {ser.agg('max')}")
print(f"Summation is: {ser.agg('sum')}")

Count is: 10000
Mean value is: 0.49415955768429964
Standard deviation is: 0.28763012652699277
Minimum value is: 1.1634755366141114e-05
Maximum value is: 0.9997176732861306
Summation is: 4941.595576842997

In [51]:
ser.agg(["min", "max"])

min    0.000012
max    0.999718
dtype: float64

In [52]:
np.random.seed(42)

df = pd.DataFrame(
    np.random.randn(10_000, 6),
    columns=list("abcdef"),
).convert_dtypes(dtype_backend="numpy_nullable")

df.head()

          a         b         c         d         e         f
0  0.496714 -0.138264  0.647689   1.52303 -0.234153 -0.234137
1  1.579213  0.767435 -0.469474   0.54256 -0.463418  -0.46573
2  0.241962  -1.91328 -1.724918 -0.562288 -1.012831  0.314247
3 -0.908024 -1.412304  1.465649 -0.225776  0.067528 -1.424748
4 -0.544383  0.110923 -1.150994  0.375698 -0.600639 -0.291694

In [53]:
df.sum()

a    -21.365908
b     -7.963987
c    152.032992
d   -180.727498
e     29.399311
f     25.042078
dtype: Float64

In [54]:
df.sum(axis=1)

0       2.060878
1       1.490586
2      -4.657107
3      -2.437675
4      -2.101088
          ...
9995     5.54669
9996    3.134053
9997    1.755601
9998   -2.008404
9999   -3.314518
Length: 10000, dtype: Float64

In [65]:
df.agg(["min", "max"])

            a         b         c         d         e         f
min -4.295391 -3.436062 -3.922400 -4.465604 -3.836656 -4.157734
max  3.602415  3.745379  3.727833  4.479084  3.691625  3.942331

In [66]:
def mean_and_add_42(ser: pd.Series):
    return ser.mean() + 42

def mean_and_sub_42(ser: pd.Series):
    return ser.mean() - 42

In [67]:
np.random.seed(42)
ser = pd.Series(np.random.rand(10_000), dtype=pd.Float64Dtype())

ser.agg([mean_and_add_42, mean_and_sub_42])

mean_and_add_42    42.49416
mean_and_sub_42   -41.50584
dtype: float64