In [1]:
import numpy as np
import pandas as pd

# **Basic pd.Series arithmetic**

In [2]:
ser = pd.Series(range(3), dtype=pd.Int64Dtype())

ser

0    0
1    1
2    2
dtype: Int64

In [3]:
ser + 42

0    42
1    43
2    44
dtype: Int64

In [5]:
ser - 42

0    -42
1    -41
2    -40
dtype: Int64

In [6]:
ser * 42

0     0
1    42
2    84
dtype: Int64

In [7]:
ser / 42

0         0.0
1     0.02381
2    0.047619
dtype: Float64

In [8]:
ser2 = pd.Series(range(10, 13), dtype=pd.Int64Dtype())

ser + ser2

0    10
1    12
2    14
dtype: Int64

In [9]:
ser1 = pd.Series([1., 2., 3.], dtype=pd.Float64Dtype())
ser2 = pd.Series([4., pd.NA, 6.], dtype=pd.Float64Dtype())

ser.add(ser2)

0     4.0
1    <NA>
2     8.0
dtype: Float64

In [10]:
ser1.add(ser2, fill_value=0)

0    5.0
1    2.0
2    9.0
dtype: Float64

In [11]:
ser1 = pd.Series(range(3), dtype=pd.Int64Dtype())
ser2 = pd.Series(range(3), dtype=pd.Int64Dtype())

ser1 + ser2

0    0
1    2
2    4
dtype: Int64

In [12]:
ser3 = pd.Series([2, 4], dtype=pd.Int64Dtype())

ser1 + ser3

0       2
1       5
2    <NA>
dtype: Int64

In [13]:
ser4 = pd.Series([2, 4, 8], index=[1, 2, 3], dtype=pd.Int64Dtype())

ser1 + ser4

0    <NA>
1       3
2       6
3    <NA>
dtype: Int64

In [14]:
ser5 = pd.Series([2, 4, 8], index=[0, 1, 1], dtype=pd.Int64Dtype())

ser1 + ser5

0       2
1       5
1       9
2    <NA>
dtype: Int64

In [15]:
import timeit

In [20]:
func = lambda: pd.Series(range(10000), dtype=pd.Int64Dtype()) + pd.Series(range(10000), dtype=pd.Int64Dtype())
timeit.timeit(func, number=10_000)

2.119075100000373

In [21]:
func = lambda: pd.Series(range(10_000), dtype=pd.Int64Dtype()).add(pd.Series(range(10_000), dtype=pd.Int64Dtype()))
timeit.timeit(func, number=10_000)

2.1072990929997104

# **Basic pd.DataFrame arithmetic**

In [22]:
np.random.seed(42)

df = pd.DataFrame(
    np.random.randn(3, 3),
    columns=["col1", "col2", "col3"],
    index=["row1", "row2", "row3"],
).convert_dtypes(dtype_backend="numpy_nullable")

df

          col1      col2      col3
row1  0.496714 -0.138264  0.647689
row2   1.52303 -0.234153 -0.234137
row3  1.579213  0.767435 -0.469474

In [23]:
df + 1

          col1      col2      col3
row1  1.496714  0.861736  1.647689
row2   2.52303  0.765847  0.765863
row3  2.579213  1.767435  0.530526

In [24]:
df * 2

          col1      col2      col3
row1  0.993428 -0.276529  1.295377
row2   3.04606 -0.468307 -0.468274
row3  3.158426  1.534869 -0.938949

In [25]:
ser = pd.Series(
    [20, 10, 0],
    index=["col1", "col2", "col3"],
    dtype=pd.Int64Dtype(),
)

ser

col1    20
col2    10
col3     0
dtype: Int64

In [26]:
df + ser

           col1       col2      col3
row1  20.496714   9.861736  0.647689
row2   21.52303   9.765847 -0.234137
row3  21.579213  10.767435 -0.469474

In [27]:
ser = pd.Series(
    [20, 10, 0, 42],
    index=["col1", "col2", "col3", "new_column"],
    dtype=pd.Int64Dtype(),
)

ser + df

           col1       col2      col3  new_column
row1  20.496714   9.861736  0.647689         NaN
row2   21.52303   9.765847 -0.234137         NaN
row3  21.579213  10.767435 -0.469474         NaN

In [28]:
ser = pd.Series(
    [20, 10, 0],
    index=["row1", "row2", "row3"],
    dtype=pd.Int64Dtype(),
)

ser

row1    20
row2    10
row3     0
dtype: Int64

In [29]:
df + ser

      col1  col2  col3  row1  row2  row3
row1  <NA>  <NA>  <NA>   NaN   NaN   NaN
row2  <NA>  <NA>  <NA>   NaN   NaN   NaN
row3  <NA>  <NA>  <NA>   NaN   NaN   NaN

In [30]:
ser = pd.Series(
    [20, 10, 0, 42],
    index=["row1", "row2", "row3", "row4"],
    dtype=pd.Int64Dtype(),
)

ser

row1    20
row2    10
row3     0
row4    42
dtype: Int64

In [31]:
df

          col1      col2      col3
row1  0.496714 -0.138264  0.647689
row2   1.52303 -0.234153 -0.234137
row3  1.579213  0.767435 -0.469474

In [32]:
df.add(ser, axis=0) # match up the row label

           col1       col2       col3
row1  20.496714  19.861736  20.647689
row2   11.52303   9.765847   9.765863
row3   1.579213   0.767435  -0.469474
row4       <NA>       <NA>       <NA>

In [33]:
df + df

          col1      col2      col3
row1  0.993428 -0.276529  1.295377
row2   3.04606 -0.468307 -0.468274
row3  3.158426  1.534869 -0.938949

In [35]:
np.random.seed(42)

df2 = pd.DataFrame(np.random.randn(3, 3)).convert_dtypes(dtype_backend="numpy_nullable")

df2

          0         1         2
0  0.496714 -0.138264  0.647689
1   1.52303 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474

In [36]:
df + df2

      col1  col2  col3     0     1     2
row1  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
row2  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
row3  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
0     <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1     <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
2     <NA>  <NA>  <NA>  <NA>  <NA>  <NA>

# **Aggregations**

In [37]:
np.random.seed(42)

ser = pd.Series(np.random.rand(10_000), dtype=pd.Float64Dtype())

In [38]:
print(f"Count is: {ser.count()}")
print(f"Mean value is: {ser.mean()}")
print(f"Standard deviation is: {ser.std()}")
print(f"Minimum value is: {ser.min()}")
print(f"Maximum value is: {ser.max()}")
print(f"Summation is: {ser.sum()}")

Count is: 10000
Mean value is: 0.49415955768429964
Standard deviation is: 0.28763012652699277
Minimum value is: 1.1634755366141114e-05
Maximum value is: 0.9997176732861306
Summation is: 4941.595576842997

In [46]:
# a Generic way
print(f"Count is: {ser.agg('count')}")
print(f"Mean value is: {ser.agg('mean')}")
print(f"Standard deviation is: {ser.agg('std')}")
print(f"Minimum value is: {ser.agg('min')}")
print(f"Maximum value is: {ser.agg('max')}")
print(f"Summation is: {ser.agg('sum')}")

Count is: 10000
Mean value is: 0.49415955768429964
Standard deviation is: 0.28763012652699277
Minimum value is: 1.1634755366141114e-05
Maximum value is: 0.9997176732861306
Summation is: 4941.595576842997

In [51]:
ser.agg(["min", "max"])

min    0.000012
max    0.999718
dtype: float64

In [52]:
np.random.seed(42)

df = pd.DataFrame(
    np.random.randn(10_000, 6),
    columns=list("abcdef"),
).convert_dtypes(dtype_backend="numpy_nullable")

df.head()

          a         b         c         d         e         f
0  0.496714 -0.138264  0.647689   1.52303 -0.234153 -0.234137
1  1.579213  0.767435 -0.469474   0.54256 -0.463418  -0.46573
2  0.241962  -1.91328 -1.724918 -0.562288 -1.012831  0.314247
3 -0.908024 -1.412304  1.465649 -0.225776  0.067528 -1.424748
4 -0.544383  0.110923 -1.150994  0.375698 -0.600639 -0.291694

In [53]:
df.sum()

a    -21.365908
b     -7.963987
c    152.032992
d   -180.727498
e     29.399311
f     25.042078
dtype: Float64

In [54]:
df.sum(axis=1)

0       2.060878
1       1.490586
2      -4.657107
3      -2.437675
4      -2.101088
          ...
9995     5.54669
9996    3.134053
9997    1.755601
9998   -2.008404
9999   -3.314518
Length: 10000, dtype: Float64

In [65]:
df.agg(["min", "max"])

            a         b         c         d         e         f
min -4.295391 -3.436062 -3.922400 -4.465604 -3.836656 -4.157734
max  3.602415  3.745379  3.727833  4.479084  3.691625  3.942331

In [66]:
def mean_and_add_42(ser: pd.Series):
    return ser.mean() + 42

def mean_and_sub_42(ser: pd.Series):
    return ser.mean() - 42

In [68]:
# Each callable should accept a single argument pd.Series and reduce down to a scalar
np.random.seed(42)
ser = pd.Series(np.random.rand(10_000), dtype=pd.Float64Dtype())

ser.agg([mean_and_add_42, mean_and_sub_42])

mean_and_add_42    42.49416
mean_and_sub_42   -41.50584
dtype: float64

# **Transformations**

In [70]:
ser = pd.Series([-1, 0, 1], dtype=pd.Int64Dtype())

ser

0    -1
1     0
2     1
dtype: Int64

In [71]:
def adds_one(ser: pd.Series) -> pd.Series:
    return ser + 1

In [72]:
ser.transform(["abs", adds_one])

   abs  adds_one
0    1         0
1    0         1
2    1         2

In [73]:
df = pd.DataFrame(
    np.arange(-5, 4, 1).reshape(3, -1)
).convert_dtypes(dtype_backend="numpy_nullable")

df

    0   1   2
0  -5  -4  -3
1  -2  -1   0
2   1   2   3

In [74]:
df.transform("abs") # apply the absolute value function to each column individually before piecing back together the result as a pd.DataFrame

   0  1  2
0  5  4  3
1  2  1  0
2  1  2  3

In [75]:
def add_42(ser: pd.Series):
    return ser + 42

In [77]:
df.transform(["abs", add_42]) # resulting Multi-Column

    0          1          2
  abs add_42 abs add_42 abs add_42
0   5     37   4     38   3     39
1   2     40   1     41   0     42
2   1     43   2     44   3     45

# **Map**

In [78]:
ser = pd.Series([123.45, [100, 113], 142.0, [110, 113, 119]])

ser

0             123.45
1         [100, 113]
2              142.0
3    [110, 113, 119]
dtype: object

In [79]:
def custom_average(value):
    if isinstance(value, list):
        return sum(value) / len(value)
    return value

In [84]:
ser.map(custom_average)

0    123.45
1    106.50
2    142.00
3    114.00
dtype: float64

In [81]:
df = pd.DataFrame([
    [2., [1, 2], 3.],
    [[4, 5], 5, 7.],
    [1, 4, [1, 1, 5.5]],
])

df

        0       1            2
0     2.0  [1, 2]          3.0
1  [4, 5]       5          7.0
2       1       4  [1, 1, 5.5]

In [85]:
df.map(custom_average)

     0    1    2
0  2.0  1.5  3.0
1  4.5  5.0  7.0
2  1.0  4.0  2.5

In [86]:
ser.transform(custom_average)

0    123.45
1    106.50
2    142.00
3    114.00
dtype: float64

> **pd.DataFrame.transform** essentially loops over each column and passes that column as an argument to the callable arguments.

In [87]:
df.transform(custom_average)

        0       1            2
0     2.0  [1, 2]          3.0
1  [4, 5]       5          7.0
2       1       4  [1, 1, 5.5]

In [91]:
def custom_average_df(value):
    if isinstance(value, pd.Series):
        return value.transform(custom_average)
    return value

In [92]:
df.transform(custom_average_df)

     0    1    2
0  2.0  1.5  3.0
1  4.5  5.0  7.0
2  1.0  4.0  2.5

In [94]:
def custom_average_df1(value):
    if isinstance(value, (pd.Series, pd.DataFrame)):
        raise TypeError("Received a pandas object - expected a single value!")
    if isinstance(value, list):
        return sum(value) / len(value)
    return value

In [95]:
df.transform(custom_average_df1)

TypeError: Received a pandas object - expected a single value!

# **Apply**

In [97]:
def debug_apply(value):
    print(f"Apply was called with value:\n{value}")

In [98]:
ser = pd.Series(range(3), dtype=pd.Int64Dtype())

ser.apply(debug_apply)

Apply was called with value:
0
Apply was called with value:
1
Apply was called with value:
2

0    None
1    None
2    None
dtype: object

In [100]:
ser.map(debug_apply)

Apply was called with value:
0
Apply was called with value:
1
Apply was called with value:
2

0    None
1    None
2    None
dtype: object

In [101]:
df = pd.DataFrame(
    np.arange(6).reshape(3, -1),
    columns=list("ab"),
).convert_dtypes(dtype_backend="numpy_nullable")

df

   a  b
0  0  1
1  2  3
2  4  5

In [102]:
df.apply(debug_apply)

Apply was called with value:
0    0
1    2
2    4
Name: a, dtype: Int64
Apply was called with value:
0    1
1    3
2    5
Name: b, dtype: Int64

a    None
b    None
dtype: object

In [103]:
def debug_apply_and_return(value):
    print(value)
    return value

In [104]:
df.apply(debug_apply_and_return)

0    0
1    2
2    4
Name: a, dtype: Int64
0    1
1    3
2    5
Name: b, dtype: Int64

   a  b
0  0  1
1  2  3
2  4  5

# **Summary statistics**

In [105]:
ser = pd.Series(["a", "b", "c", "a", "c", "a"], dtype=pd.StringDtype())

ser.value_counts()

a    3
c    2
b    1
Name: count, dtype: Int64

In [107]:
ser = pd.Series([0, 42, 84], dtype=pd.Int64Dtype())

ser.describe()

count     3.0
mean     42.0
std      42.0
min       0.0
25%      21.0
50%      42.0
75%      63.0
max      84.0
dtype: Float64

In [108]:
ser.describe(percentiles=[.10, .44, .67])

count      3.0
mean      42.0
std       42.0
min        0.0
10%        8.4
44%      36.96
50%       42.0
67%      56.28
max       84.0
dtype: Float64

# **Binning algorithms**

In [2]:
df = pd.DataFrame([
    ["Jane", 34],
    ["John", 18],
    ["Jamie", 22],
    ["Jessica", 36],
    ["Jackie", 33],
    ["Steve", 40],
    ["Sam", 30],
    ["Stephanie", 66],
    ["Sarah", 55],
    ["Aaron", 22],
    ["Erin", 28],
    ["Elsa", 37],
], columns=["name", "age"]).convert_dtypes(dtype_backend="numpy_nullable")

df.head()

      name  age
0     Jane   34
1     John   18
2    Jamie   22
3  Jessica   36
4   Jackie   33

In [3]:
pd.cut(df["age"], bins=4)

0       (30.0, 42.0]
1     (17.952, 30.0]
2     (17.952, 30.0]
3       (30.0, 42.0]
4       (30.0, 42.0]
5       (30.0, 42.0]
6     (17.952, 30.0]
7       (54.0, 66.0]
8       (54.0, 66.0]
9     (17.952, 30.0]
10    (17.952, 30.0]
11      (30.0, 42.0]
Name: age, dtype: category
Categories (4, interval[float64, right]): [(17.952, 30.0] < (30.0, 42.0] < (42.0, 54.0] < (54.0, 66.0]]

In [4]:
pd.cut(df["age"], bins=4, precision=0)

0     (30.0, 42.0]
1     (18.0, 30.0]
2     (18.0, 30.0]
3     (30.0, 42.0]
4     (30.0, 42.0]
5     (30.0, 42.0]
6     (18.0, 30.0]
7     (54.0, 66.0]
8     (54.0, 66.0]
9     (18.0, 30.0]
10    (18.0, 30.0]
11    (30.0, 42.0]
Name: age, dtype: category
Categories (4, interval[float64, right]): [(18.0, 30.0] < (30.0, 42.0] < (42.0, 54.0] < (54.0, 66.0]]

In [5]:
pd.cut(df["age"], bins=[10, 20, 30, 40, 50, 60, 70])

0     (30, 40]
1     (10, 20]
2     (20, 30]
3     (30, 40]
4     (30, 40]
5     (30, 40]
6     (20, 30]
7     (60, 70]
8     (50, 60]
9     (20, 30]
10    (20, 30]
11    (30, 40]
Name: age, dtype: category
Categories (6, interval[int64, right]): [(10, 20] < (20, 30] < (30, 40] < (40, 50] < (50, 60] < (60, 70]]

In [6]:
pd.cut(df["age"], [10, 20, 30, 40, 50, 60, 999])

0      (30, 40]
1      (10, 20]
2      (20, 30]
3      (30, 40]
4      (30, 40]
5      (30, 40]
6      (20, 30]
7     (60, 999]
8      (50, 60]
9      (20, 30]
10     (20, 30]
11     (30, 40]
Name: age, dtype: category
Categories (6, interval[int64, right]): [(10, 20] < (20, 30] < (30, 40] < (40, 50] < (50, 60] < (60, 999]]

In [8]:
pd.cut(
    df["age"],
    bins=[10, 20, 30, 40, 50, 60, 999],
    labels=["10-20", "20-30", "30-40", "40-50", "50-60", "60+"]
)

0     30-40
1     10-20
2     20-30
3     30-40
4     30-40
5     30-40
6     20-30
7       60+
8     50-60
9     20-30
10    20-30
11    30-40
Name: age, dtype: category
Categories (6, object): ['10-20' < '20-30' < '30-40' < '40-50' < '50-60' < '60+']

In [9]:
df.assign(age_bin=lambda x: pd.cut(x["age"], [10, 20, 30, 40, 50, 60, 999]))

         name  age    age_bin
0        Jane   34   (30, 40]
1        John   18   (10, 20]
2       Jamie   22   (20, 30]
3     Jessica   36   (30, 40]
4      Jackie   33   (30, 40]
5       Steve   40   (30, 40]
6         Sam   30   (20, 30]
7   Stephanie   66  (60, 999]
8       Sarah   55   (50, 60]
9       Aaron   22   (20, 30]
10       Erin   28   (20, 30]
11       Elsa   37   (30, 40]

In [11]:
df.assign(
    age_bin=lambda x: pd.cut(
        x["age"], 
        bins=[10, 20, 30, 40, 50, 60, 999], 
        right=False)
)

         name  age    age_bin
0        Jane   34   [30, 40)
1        John   18   [10, 20)
2       Jamie   22   [20, 30)
3     Jessica   36   [30, 40)
4      Jackie   33   [30, 40)
5       Steve   40   [40, 50)
6         Sam   30   [30, 40)
7   Stephanie   66  [60, 999)
8       Sarah   55   [50, 60)
9       Aaron   22   [20, 30)
10       Erin   28   [20, 30)
11       Elsa   37   [30, 40)

# **One-hot encoding with `pd.get_dummies`**

In [12]:
ser = pd.Series([
    "green",
    "brown",
    "blue","amber",
    "hazel",
    "amber",
    "green",
    "blue",
    "green",
], name="eye_colors", dtype=pd.StringDtype())

ser

0    green
1    brown
2     blue
3    amber
4    hazel
5    amber
6    green
7     blue
8    green
Name: eye_colors, dtype: string

In [14]:
pd.get_dummies(ser, dtype=pd.Int8Dtype())

   amber  blue  brown  green  hazel
0      0     0      0      1      0
1      0     0      1      0      0
2      0     1      0      0      0
3      1     0      0      0      0
4      0     0      0      0      1
5      1     0      0      0      0
6      0     0      0      1      0
7      0     1      0      0      0
8      0     0      0      1      0

In [16]:
pd.get_dummies(ser, prefix="is_")

   is__amber  is__blue  is__brown  is__green  is__hazel
0      False     False      False       True      False
1      False     False       True      False      False
2      False      True      False      False      False
3       True     False      False      False      False
4      False     False      False      False       True
5       True     False      False      False      False
6      False     False      False       True      False
7      False      True      False      False      False
8      False     False      False       True      False

# **Chaining with `.pipe`**

In [17]:
df = pd.DataFrame({
    "col1": pd.Series([1, 2, 3], dtype=pd.Int64Dtype()),
    "col2": pd.Series(["a", "b", "c"], dtype=pd.StringDtype())
})

df

   col1 col2
0     1    a
1     2    b
2     3    c

In [19]:
def change_col1(df: pd.DataFrame) -> pd.DataFrame:
    return df.assign(col1=pd.Series([4, 5, 6], dtype=pd.Int64Dtype()))

def change_col2(df: pd.DataFrame) -> pd.DataFrame:
    return df.assign(col2=pd.Series(["X", "Y", "Z"], dtype=pd.StringDtype()))

In [20]:
df2 = change_col1(df)
df3 = change_col2(df2)

df3

   col1 col2
0     4    X
1     5    Y
2     6    Z

In [21]:
change_col2(change_col1(df))

   col1 col2
0     4    X
1     5    Y
2     6    Z

In [23]:
(
    df
    .pipe(change_col1)
    .pipe(change_col2)
)

   col1 col2
0     4    X
1     5    Y
2     6    Z

In [24]:
from typing import Literal

In [25]:
def change_col2(
    df: pd.DataFrame,
    str_case: Literal["upper", "lower"]
    ) -> pd.DataFrame:
    if str_case == "upper":
        values = ["X", "Y", "Z"]
    else:
        values = ["x", "y", "z"]
    
    return df.assign(col2=pd.Series(values, dtype=pd.StringDtype()))

In [26]:
(
    df
    .pipe(change_col1)
    .pipe(change_col2, str_case="lower")
)

   col1 col2
0     4    x
1     5    y
2     6    z

# **Selecting the lowest-budget movies from the top 100**

In [27]:
df = pd.read_csv(
    "../Datasets/movie.csv",
    usecols=["movie_title", "imdb_score", "budget", "gross"],
    dtype_backend="numpy_nullable"
)

df.head()

,gross,movie_title,budget,imdb_score
0,760505847.0,Avatar,237000000.0,7.9
1,309404152.0,Pirates of the Caribbean: At World's End,300000000.0,7.1
2,200074175.0,Spectre,245000000.0,6.8
3,448130642.0,The Dark Knight Rises,250000000.0,8.5
4,<NA>,Star Wars: Episode VII - The Force Awakens,<NA>,7.1

In [30]:
df.nlargest(100, "imdb_score").head()

            gross               movie_title      budget  imdb_score
2725         <NA>          Towering Inferno        <NA>         9.5
1920   28341469.0  The Shawshank Redemption  25000000.0         9.3
3402  134821952.0             The Godfather   6000000.0         9.2
2779     447093.0                   Dekalog        <NA>         9.1
4312         <NA>      Kickboxer: Vengeance  17000000.0         9.1

In [31]:
df.nlargest(100, "imdb_score").nsmallest(5, "budget")

          gross           movie_title    budget  imdb_score
4804       <NA>        Butterfly Girl  180000.0         8.7
4801   925402.0    Children of Heaven  180000.0         8.5
4706       <NA>          12 Angry Men  350000.0         8.9
4550  7098492.0          A Separation  500000.0         8.4
4636   133778.0  The Other Dream Team  500000.0         8.4

In [32]:
df.nlargest(10, "imdb_score")

,gross,movie_title,budget,imdb_score
2725,<NA>,Towering Inferno,<NA>,9.5
1920,28341469.0,The Shawshank Redemption,25000000.0,9.3
3402,134821952.0,The Godfather,6000000.0,9.2
2779,447093.0,Dekalog,<NA>,9.1
4312,<NA>,Kickboxer: Vengeance,17000000.0,9.1
66,533316061.0,The Dark Knight,185000000.0,9.0
2791,57300000.0,The Godfather: Part II,13000000.0,9.0
3415,<NA>,Fargo,<NA>,9.0
335,377019252.0,The Lord of the Rings: The Return of the King,94000000.0,8.9
1857,96067179.0,Schindler's List,22000000.0,8.9

In [33]:
df[df["imdb_score"] >= 8.9]

,gross,movie_title,budget,imdb_score
66,533316061.0,The Dark Knight,185000000.0,9.0
335,377019252.0,The Lord of the Rings: The Return of the King,94000000.0,8.9
1857,96067179.0,Schindler's List,22000000.0,8.9
1920,28341469.0,The Shawshank Redemption,25000000.0,9.3
2725,<NA>,Towering Inferno,<NA>,9.5
2779,447093.0,Dekalog,<NA>,9.1
2791,57300000.0,The Godfather: Part II,13000000.0,9.0
3295,107930000.0,Pulp Fiction,8000000.0,8.9
3402,134821952.0,The Godfather,6000000.0,9.2
3415,<NA>,Fargo,<NA>,9.0
4312,<NA>,Kickboxer: Vengeance,17000000.0,9.1
4397,6100000.0,"The Good, the Bad and the Ugly",1200000.0,8.9
4706,<NA>,12 Angry Men,350000.0,8.9

In [34]:
df.nlargest(10, ["imdb_score", "gross"])

,gross,movie_title,budget,imdb_score
2725,<NA>,Towering Inferno,<NA>,9.5
1920,28341469.0,The Shawshank Redemption,25000000.0,9.3
3402,134821952.0,The Godfather,6000000.0,9.2
2779,447093.0,Dekalog,<NA>,9.1
4312,<NA>,Kickboxer: Vengeance,17000000.0,9.1
66,533316061.0,The Dark Knight,185000000.0,9.0
2791,57300000.0,The Godfather: Part II,13000000.0,9.0
3415,<NA>,Fargo,<NA>,9.0
335,377019252.0,The Lord of the Rings: The Return of the King,94000000.0,8.9
3295,107930000.0,Pulp Fiction,8000000.0,8.9

# **Calculating a trailing stop order price**

In [45]:
df = pd.read_csv(
    "../Datasets/NVDA.csv",
    usecols=["Date", "Close"],
    date_parser=lambda x: pd.to_datetime(x),
    index_col=["Date"],
    dtype_backend="numpy_nullable",
)

df.head()

/tmp/ipykernel_4613/4273972237.py:1: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(

                Close
Date
2020-01-02  59.977501
2020-01-03  59.017502
2020-01-06  59.264999
2020-01-07  59.982498
2020-01-08  60.095001

In [46]:
df = pd.read_csv(
    "../Datasets/NVDA.csv",
    usecols=["Date", "Close"],
    parse_dates=["Date"],
    index_col=["Date"],
).convert_dtypes(dtype_backend="numpy_nullable")

df.head()

                Close
Date
2020-01-02  59.977501
2020-01-03  59.017502
2020-01-06  59.264999
2020-01-07  59.982498
2020-01-08  60.095001

In [48]:
ser = df.squeeze() # reduce the dimension to 1 dimension

ser

Date
2020-01-02     59.977501
2020-01-03     59.017502
2020-01-06     59.264999
2020-01-07     59.982498
2020-01-08     60.095001
                 ...
2023-12-22    488.299988
2023-12-26    492.790009
2023-12-27    494.170013
2023-12-28    495.220001
2023-12-29    495.220001
Name: Close, Length: 1006, dtype: Float64

In [51]:
ser_cummax = ser.cummax()

ser_cummax.head()

Date
2020-01-02    59.977501
2020-01-03    59.977501
2020-01-06    59.977501
2020-01-07    59.982498
2020-01-08    60.095001
Name: Close, dtype: Float64

In [52]:
ser.cummax().mul(0.9).head()

Date
2020-01-02    53.979751
2020-01-03    53.979751
2020-01-06    53.979751
2020-01-07    53.984248
2020-01-08    54.085501
Name: Close, dtype: Float64

In [53]:
ser.cummin().mul(1.1).head()

Date
2020-01-02    65.975251
2020-01-03    64.919252
2020-01-06    64.919252
2020-01-07    64.919252
2020-01-08    64.919252
Name: Close, dtype: Float64

In [54]:
stop_prices = ser.cummax().mul(0.9)

ser[ser <= stop_prices]

Date
2020-02-24         68.32
2020-02-25     65.512497
2020-02-26     66.912498
2020-02-27     63.150002
2020-02-28     67.517502
                 ...
2023-10-27         405.0
2023-10-30    411.609985
2023-10-31    407.799988
2023-11-01        423.25
2023-11-02    435.059998
Name: Close, Length: 495, dtype: Float64

In [58]:
(ser <= stop_prices).idxmax()

Timestamp('2020-02-24 00:00:00')

# **Finding the baseball players best at...**

In [61]:
df = pd.read_parquet(
    "../Datasets/mlb_batting_summaries.parquet",
).set_index("id")

df

           ab    r    h  hr
id
abadf001    0    0    0   0
abboa001    0    0    0   0
abboc001    3    0    1   0
abrac001  847  116  208  20
abrea001    0    0    0   0
...       ...  ...  ...  ..
zimmk001    0    0    0   0
zimmr001  255   27   62  14
zubet001    1    0    0   0
zunig001    0    0    0   0
zunim001  572   82  111  41

[2183 rows x 4 columns]

In [62]:
df.idxmax()

ab    semim001
r     freef001
h     freef001
hr    judga001
dtype: string

In [65]:
best_players = df.idxmax().unique()
mask = df.index.isin(best_players)

df[mask]

            ab    r    h   hr
id
freef001  1849  368  590   81
judga001  1487  301  433  138
semim001  1979  338  521  100

In [66]:
df[mask].style.highlight_max()

# **Understanding which position scores the most per team**