In [2]:
import numpy as np
import pandas as pd

# **Concatenating `pd.DataFrame` objects**

In [3]:
df_q1 = pd.DataFrame([
    ["AAPL", 100., 50., 75.],
    ["MSFT", 80., 42., 62.],
    ["AMZN", 60., 100., 120.],
], columns=["ticker", "shares", "low", "high"]).convert_dtypes(dtype_backend="numpy_nullable")

df_q1

  ticker  shares  low  high
0   AAPL     100   50    75
1   MSFT      80   42    62
2   AMZN      60  100   120

In [4]:
df_q2 = pd.DataFrame([
    ["AAPL", 80., 70., 80., 77.],
    ["MSFT", 90., 50., 60., 55.],
    ["IBM", 100., 60., 70., 64.],
    ["GE", 42., 30., 50., 44.],
], columns=["ticker", "shares", "low", "high", "close"]).convert_dtypes(dtype_backend="numpy_nullable")

df_q2

  ticker  shares  low  high  close
0   AAPL      80   70    80     77
1   MSFT      90   50    60     55
2    IBM     100   60    70     64
3     GE      42   30    50     44

In [6]:
pd.concat([df_q1, df_q2]) # concate method by defualt make the concatenation vertically

  ticker  shares  low  high  close
0   AAPL     100   50    75   <NA>
1   MSFT      80   42    62   <NA>
2   AMZN      60  100   120   <NA>
0   AAPL      80   70    80     77
1   MSFT      90   50    60     55
2    IBM     100   60    70     64
3     GE      42   30    50     44

In [8]:
pd.concat(
    [df_q1, df_q2],
    ignore_index=True
)

  ticker  shares  low  high  close
0   AAPL     100   50    75   <NA>
1   MSFT      80   42    62   <NA>
2   AMZN      60  100   120   <NA>
3   AAPL      80   70    80     77
4   MSFT      90   50    60     55
5    IBM     100   60    70     64
6     GE      42   30    50     44

In [10]:
pd.concat(
    [df_q1, df_q2],
    # ignore_index=True,
    keys=["q1", "q2"]
)

     ticker  shares  low  high  close
q1 0   AAPL     100   50    75   <NA>
   1   MSFT      80   42    62   <NA>
   2   AMZN      60  100   120   <NA>
q2 0   AAPL      80   70    80     77
   1   MSFT      90   50    60     55
   2    IBM     100   60    70     64
   3     GE      42   30    50     44

In [13]:
pd.concat(
    [df_q1, df_q2],
    keys=["q1", "q2"],
    axis=1
)

      q1                        q2
  ticker shares   low  high ticker shares low high close
0   AAPL    100    50    75   AAPL     80  70   80    77
1   MSFT     80    42    62   MSFT     90  50   60    55
2   AMZN     60   100   120    IBM    100  60   70    64
3   <NA>   <NA>  <NA>  <NA>     GE     42  30   50    44

In [14]:
pd.concat(
    [
        df_q1.set_index("ticker"), 
        df_q2.set_index("ticker")
    ],
    keys=["q1", "q2"],
    axis=1
)

           q1                 q2
       shares   low  high shares   low  high close
ticker
AAPL      100    50    75     80    70    80    77
MSFT       80    42    62     90    50    60    55
AMZN       60   100   120   <NA>  <NA>  <NA>  <NA>
IBM      <NA>  <NA>  <NA>    100    60    70    64
GE       <NA>  <NA>  <NA>     42    30    50    44

In [15]:
pd.concat(
    [
        df_q1.set_index("ticker"), 
        df_q2.set_index("ticker")
    ],
    keys=["q1", "q2"],
    axis=1,
    join='inner'
)

           q1              q2
       shares low high shares low high close
ticker
AAPL      100  50   75     80  70   80    77
MSFT       80  42   62     90  50   60    55

> **`pd.concat`** is an expensive operation, and should never be called from within a Python loop.

In [16]:
%%time
concatenated_dfs = df_q1

for i in range(1_000):
    concatenated_dfs = pd.concat([concatenated_dfs, df_q1])

print(f"Final pd.DataFrame shape is {concatenated_dfs.shape}")

Final pd.DataFrame shape is (3003, 4)
CPU times: user 388 ms, sys: 0 ns, total: 388 ms
Wall time: 388 ms

In [19]:
%%time

df = df_q1
accumulated = [df_q1]

for i in range(1000):
    accumulated.append(df_q1)

concatenated_dfs = pd.concat(accumulated)

print(f"Final pd.DataFrame shape is {concatenated_dfs.shape}")

Final pd.DataFrame shape is (3003, 4)
CPU times: user 85.6 ms, sys: 3.19 ms, total: 88.8 ms
Wall time: 87.1 ms

# **Merging DataFrames with `pd.merge`**