In [2]:
import datetime as dt
import numpy as np
import pandas as pd

# **Pandas Data Structures**

In [2]:
data = np.genfromtxt(
    '../Datasets/example_data.csv',
    delimiter=';',
    names=True,
    dtype=None,
    encoding='UTF'
)

data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [3]:
data.shape

(5,)

In [4]:
data.dtype

dtype([('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [5]:
%%timeit
max([row[3] for row in data])

3.77 μs ± 143 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [6]:
data.dtype.names

('time', 'place', 'magType', 'mag', 'alert', 'tsunami')

In [7]:
for i, col in enumerate(data.dtype.names): print(i, "==>", col)

0 ==> time
1 ==> place
2 ==> magType
3 ==> mag
4 ==> alert
5 ==> tsunami

In [8]:
array_dict = {
    col: np.array([row[i] for row in data])
    for i, col in enumerate(data.dtype.names)
}

array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [9]:
%%timeit
array_dict['mag'].max()

1.56 μs ± 144 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [10]:
np.array([
    value[array_dict['mag'].argmax()]
    for key, value in array_dict.items()
])

array(['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
       'mww', '6.7', 'green', '1'], dtype='<U32')

## **Series**

In [11]:
place = pd.Series(array_dict['place'], name='place')

place

0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

!['Commonly used series attributes'](../Images/Commonly_used_series_attributes.png)

In [12]:
place.name, place.dtype, place.shape, place.index, place.values

('place',
 dtype('O'),
 (5,),
 RangeIndex(start=0, stop=5, step=1),
 array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype=object))

> **Important note** : For the most part, pandas objects use NumPy arrays for their internal data representations. However, for some data types, pandas builds upon NumPy to create its own arrays (https://pandas.pydata.org/pandas-docs/stable/reference/arrays.html). For this reason, depending on the data type, values can return either a pandas.array or a numpy.array object. Therefore, if we need to ensure we get a specific type back, it is recommended to use the array attribute or to_numpy() method, respectively, instead of values.

## **Index**

In [13]:
place_index = place.index

place_index

RangeIndex(start=0, stop=5, step=1)

In [14]:
place_index.values

array([0, 1, 2, 3, 4])

![Commonly used index attributes](../Images/Commonly_used_index_attributes.png)

In [15]:
place_index.name, place_index.dtype, place_index.shape, place_index.values, place_index.is_unique

(None, dtype('int64'), (5,), array([0, 1, 2, 3, 4]), True)

In [16]:
np.array([1, 0, 1]) + np.array([-1, 1, 1])

array([0, 1, 2])

In [17]:
numbers = np.linspace(0, 10, num=5)

numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
x = pd.Series(numbers) # index is [0, 1, 2, 3, 4]
y = pd.Series(numbers, index=pd.Index([1, 2, 3, 4, 5]))

In [19]:
x

0     0.0
1     2.5
2     5.0
3     7.5
4    10.0
dtype: float64

In [20]:
y

1     0.0
2     2.5
3     5.0
4     7.5
5    10.0
dtype: float64

In [21]:
x + y

0     NaN
1     2.5
2     7.5
3    12.5
4    17.5
5     NaN
dtype: float64

## **DataFrame**

In [22]:
array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [23]:
df = pd.DataFrame(array_dict)

df

,time,place,magType,mag,alert,tsunami
0,2018-10-13 11:10:23.560,"262km NW of Ozernovskiy, Russia",mww,6.7,green,1
1,2018-10-13 04:34:15.580,"25km E of Bitung, Indonesia",mww,5.2,green,0
2,2018-10-13 00:13:46.220,"42km WNW of Sola, Vanuatu",mww,5.7,green,0
3,2018-10-12 21:09:49.240,"13km E of Nueva Concepcion, Guatemala",mww,5.7,green,0
4,2018-10-12 02:52:03.620,"128km SE of Kimbe, Papua New Guinea",mww,5.6,green,1

![Commonly used dataframe attributes](../Images/Commonly_used_dataframe_attributes.png)

In [24]:
df.dtypes

time        object
place       object
magType     object
mag        float64
alert       object
tsunami      int64
dtype: object

In [25]:
df.shape

(5, 6)

In [26]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [27]:
df.columns

Index(['time', 'place', 'magType', 'mag', 'alert', 'tsunami'], dtype='object')

In [28]:
df.values

array([['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
        'mww', 6.7, 'green', 1],
       ['2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww',
        5.2, 'green', 0],
       ['2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww',
        5.7, 'green', 0],
       ['2018-10-12 21:09:49.240',
        '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0],
       ['2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea',
        'mww', 5.6, 'green', 1]], dtype=object)

In [29]:
df.empty

False

In [30]:
df + df

,time,place,magType,mag,alert,tsunami
0,2018-10-13 11:10:23.5602018-10-13 11:10:23.560,"262km NW of Ozernovskiy, Russia262km NW of Oze...",mwwmww,13.4,greengreen,2
1,2018-10-13 04:34:15.5802018-10-13 04:34:15.580,"25km E of Bitung, Indonesia25km E of Bitung, I...",mwwmww,10.4,greengreen,0
2,2018-10-13 00:13:46.2202018-10-13 00:13:46.220,"42km WNW of Sola, Vanuatu42km WNW of Sola, Van...",mwwmww,11.4,greengreen,0
3,2018-10-12 21:09:49.2402018-10-12 21:09:49.240,"13km E of Nueva Concepcion, Guatemala13km E of...",mwwmww,11.4,greengreen,0
4,2018-10-12 02:52:03.6202018-10-12 02:52:03.620,"128km SE of Kimbe, Papua New Guinea128km SE of...",mwwmww,11.2,greengreen,2

# **Creating a pandas DataFrame**

## **From a Python object**

In [31]:
np.random.seed(0)
pd.Series(np.random.rand(5), name="random") #  uniform distribution

0    0.548814
1    0.715189
2    0.602763
3    0.544883
4    0.423655
Name: random, dtype: float64

In [32]:
np.random.seed(0)

pd.DataFrame( # Creating DataFrame From dictionary
    {
        'random': np.random.rand(5),
        'text': ['hot', 'warm', 'cool', 'cold', None],
        'truth': [np.random.choice([True, False]) for _ in range(5)]
    },
    index=pd.date_range(
        end=dt.date(2019, 4, 21),
        freq='1D',
        periods=5, 
        name='data'
    )
)

              random  text  truth
data
2019-04-17  0.548814   hot  False
2019-04-18  0.715189  warm   True
2019-04-19  0.602763  cool   True
2019-04-20  0.544883  cold  False
2019-04-21  0.423655  None   True

In [33]:
pd.DataFrame([ # Creating DataFarme from list of dictionaries
    {'mag': 5.2, 'place': 'California'}, 
    {'mag': 1.2, 'place': 'Alaska'}, 
    {'mag': 0.2, 'place': 'California'},]
            )

   mag       place
0  5.2  California
1  1.2      Alaska
2  0.2  California

In [34]:
list_of_tuples = [(n, n**2, n**3) for n in range(5)]

list_of_tuples

[(0, 0, 0), (1, 1, 1), (2, 4, 8), (3, 9, 27), (4, 16, 64)]

In [35]:
pd.DataFrame( # Creating DataFram fro list of Tuples
    list_of_tuples,
    columns=['n', 'n_squared', 'n_cubes']
)

   n  n_squared  n_cubes
0  0          0        0
1  1          1        1
2  2          4        8
3  3          9       27
4  4         16       64

In [36]:
pd.DataFrame( # Creating DataFrame from Numpy Array
    np.array([
        [0, 0, 0], 
        [1, 1, 1], 
        [2, 4, 8], 
        [3, 9, 27], 
        [4, 16, 64]]
            ),
    columns = ['n', 'n_squared', 'n_cubes']
)

   n  n_squared  n_cubes
0  0          0        0
1  1          1        1
2  2          4        8
3  3          9       27
4  4         16       64

## **From a file**

In [37]:
# Counting Number of Lines
!wc -l ../Datasets/earthquakes.csv

9333 ../Datasets/earthquakes.csv

In [38]:
# Get Size of File
!ls -lh ../Datasets | grep earthquakes.csv

-rw-rw-r-- 1 el7m7 el7m7 3.4M Jul 18 07:51 earthquakes.csv

In [39]:
# Another way
files = !ls -lh ../Datasets
file = [file for file in files if 'earthquakes' in file]

file

['-rw-rw-r-- 1 el7m7 el7m7 3.4M Jul 18 07:51 earthquakes.csv']

In [40]:
# Inspecting existing of haeder
!head -n 2 ../Datasets/earthquakes.csv

alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,mmi,net,nst,place,rms,sig,sources,status,time,title,tsunami,type,types,tz,updated,url
,,37389218,https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=ci37389218&format=geojson,0.008693,,85.0,",ci37389218,",1.35,ml,,ci,26.0,"9km NE of Aguanga, CA",0.19,28,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventpage/ci37389218

In [41]:
# Counting The Number of Columns
!awk -F',' '{print NF; exit}' ../Datasets/earthquakes.csv

26

In [42]:
header = !head -n 1 ../Datasets/earthquakes.csv
nbr_column = len(header[0].split(','))

nbr_column

26

In [43]:
df = pd.read_csv('../Datasets/earthquakes.csv')

df

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,NaN,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018060,NaN,185.0,",nc73086771,",0.62,md,...,",nc,",reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...
9328,NaN,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410,NaN,50.0,",ci38063967,",1.00,ml,...,",ci,",reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.452600,NaN,276.0,",pr2018261000,",2.40,md,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018650,NaN,61.0,",ci38063959,",1.10,ml,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980,NaN,39.0,",ci38063935,",0.66,ml,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

![Helpful parameters when reading data from a file](../Images/Helpful_parameters_when_reading_data_from_a_file.png)

In [45]:
df.to_csv("output.csv", index=False)

## **From a database**

In [46]:
import sqlite3

In [48]:
with sqlite3.connect('../Datasets/quakes.db') as connection:
    pd.read_csv('../Datasets/tsunamis.csv').to_sql(
        'tsunamis',
        connection,
        index=False,
        if_exists='replace'
    )

In [49]:
with sqlite3.connect('../Datasets/quakes.db') as connection:
    tsunamis = pd.read_sql(
        'SELECT * FROM tsunamis', 
        connection
    )

In [50]:
tsunamis.head()

,alert,type,title,place,magType,mag,time
0,None,earthquake,"M 5.0 - 165km NNW of Flying Fish Cove, Christm...","165km NNW of Flying Fish Cove, Christmas Island",mww,5.0,1539459504090
1,green,earthquake,"M 6.7 - 262km NW of Ozernovskiy, Russia","262km NW of Ozernovskiy, Russia",mww,6.7,1539429023560
2,green,earthquake,"M 5.6 - 128km SE of Kimbe, Papua New Guinea","128km SE of Kimbe, Papua New Guinea",mww,5.6,1539312723620
3,green,earthquake,"M 6.5 - 148km S of Severo-Kuril'sk, Russia","148km S of Severo-Kuril'sk, Russia",mww,6.5,1539213362130
4,green,earthquake,"M 6.2 - 94km SW of Kokopo, Papua New Guinea","94km SW of Kokopo, Papua New Guinea",mww,6.2,1539208835130

## **From an API**

In [51]:
import requests

In [61]:
yesterday = dt.date.today() - dt.timedelta(days=1)
api = 'https://earthquake.usgs.gov/fdsnws/event/1/query'
payload = {
    'format': 'geojson',
    'starttime': yesterday - dt.timedelta(days=30),
    'endtime': yesterday
}

response = requests.get(api, params=payload)

In [62]:
response.status_code

200

In [64]:
earthquake_json = response.json()

earthquake_json.keys()

dict_keys(['type', 'metadata', 'features', 'bbox'])

In [65]:
earthquake_json['metadata']

{'generated': 1784396253000,
 'url': 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2026-06-17&endtime=2026-07-17',
 'title': 'USGS Earthquakes',
 'status': 200,
 'api': '2.7.0',
 'count': 10850}

In [66]:
earthquake_json['features']

[{'type': 'Feature',
  'properties': {'mag': 0.94,
   'place': '155 km W of Adak, Alaska',
   'time': 1784246163010,
   'updated': 1784331915180,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/av94313543',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=av94313543&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 14,
   'net': 'av',
   'code': '94313543',
   'ids': ',av94313543,',
   'sources': ',av,',
   'types': ',origin,phase-data,',
   'nst': 0,
   'dmin': 0.02037,
   'rms': 0.07,
   'gap': 290,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.9 - 155 km W of Adak, Alaska'},
  'geometry': {'type': 'Point',
   'coordinates': [-178.882166666667, 51.7903333333333, 0]},
  'id': 'av94313543'},
 {'type': 'Feature',
  'properties': {'mag': 1.8,
   'place': '19 km WSW of Anchor Point, Alaska',
   'time': 1784245212327,
   'updated': 1784274027912,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/aka2026nzvqud',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=aka2026nzvqud&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 50,
   'net': 'ak',
   'code': 'a2026nzvqud',
   'ids': ',aka2026nzvqud,',
   'sources': ',ak,',
   'types': ',origin,phase-data,',
   'nst': 29,
   'dmin': 0.5,
   'rms': 0.6,
   'gap': 75,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.8 - 19 km WSW of Anchor Point, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-152.159, 59.708, 67.2]},
  'id': 'aka2026nzvqud'},
 {'type': 'Feature',
  'properties': {'mag': 4.4,
   'place': 'south of the Fiji Islands',
   'time': 1784244929037,
   'updated': 1784246052040,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000t16p',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000t16p&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 298,
   'net': 'us',
   'code': '7000t16p',
   'ids': ',us7000t16p,',
   'sources': ',us,',
   'types': ',origin,phase-data,',
   'nst': 51,
   'dmin': 5.723,
   'rms': 0.97,
   'gap': 103,
   'magType': 'mb',
   'type': 'earthquake',
   'title': 'M 4.4 - south of the Fiji Islands'},
  'geometry': {'type': 'Point', 'coordinates': [179.9611, -23.8203, 548.78]},
  'id': 'us7000t16p'},
 {'type': 'Feature',
  'properties': {'mag': 1.69,
   'place': '24 km NE of San Ardo, CA',
   'time': 1784244709490,
   'updated': 1784249247367,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc75397381',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc75397381&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 44,
   'net': 'nc',
   'code': '75397381',
   'ids': ',nc75397381,',
   'sources': ',nc,',
   'types': ',nearby-cities,origin,phase-data,scitech-link,',
   'nst': 6,
   'dmin': 0.2951,
   'rms': 0.34,
   'gap': 175,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 1.7 - 24 km NE of San Ardo, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-120.689498901367, 36.1548347473145, 11.3699998855591]},
  'id': 'nc75397381'},
 {'type': 'Feature',
  'properties': {'mag': 0.81,
   'place': '6 km WNW of Little Lake, CA',
   'time': 1784244496200,
   'updated': 1784316465386,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci40656810',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=ci40656810&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 10,
   'net': 'ci',
   'code': '40656810',
   'ids': ',ci40656810,',
   'sources': ',ci,',
   'types': ',nearby-cities,origin,phase-data,',
   'nst': 17,
   'dmin': 0.0876,
   'rms': 0.1,
   'gap': 82,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.8 - 6 km WNW of Little Lake, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-117.974833333333, 35.953, 3.78]},
  'id': 'ci40656810'},
 {'type': 'Feature',
  'properties': {'mag': 1.46,
   'place': '1 km SE of Adak, Alaska',
   'time': 1784243437720,
   'updated': 1784331644680,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/av94313483',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=av94313483&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 33,
   'net': 'av',
   'code': '94313483',
   'ids': ',av94313483,',
   'sources': ',av,',
   'types': ',origin,phase-data,',
   'nst': 10,
   'dmin': 0.1186,
   'rms': 0.13,
   'gap': 183,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.5 - 1 km SE of Adak, Alaska'},
  'geometry': {'type': 'Point',
   'coordinates': [-176.616833333333, 51.862, -0.32]},
  'id': 'av94313483'},
 {'type': 'Feature',
  'properties': {'mag': 1.3,
   'place': '6 km E of Fox, Alaska',
   'time': 1784242966131,
   'updated': 1784243141088,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/aka2026nzukio',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=aka2026nzukio&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 26,
   'net': 'ak',
   'code': 'a2026nzukio',
   'ids': ',aka2026nzukio,',
   'sources': ',ak,',
   'types': ',origin,',
   'nst': 14,
   'dmin': 0.2,
   'rms': 0.7,
   'gap': 51,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.3 - 6 km E of Fox, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-147.492, 64.967, 0.1]},
  'id': 'aka2026nzukio'},
 {'type': 'Feature',
  'properties': {'mag': 1.7,
   'place': '22 km W of Volcano, Hawaii',
   'time': 1784242935660,
   'updated': 1784243177390,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/hv75002977',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=hv75002977&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 44,
   'net': 'hv',
   'code': '75002977',
   'ids': ',hv75002977,',
   'sources': ',hv,',
   'types': ',origin,phase-data,',
   'nst': 20,
   'dmin': 0.07735,
   'rms': 0.230000004,
   'gap': 53,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 1.7 - 22 km W of Volcano, Hawaii'},
  'geometry': {'type': 'Point',
   'coordinates': [-155.447998046875, 19.4236660003662, 5.96000003814697]},
  'id': 'hv75002977'},
 {'type': 'Feature',
  'properties': {'mag': 3.3,
   'place': '24 km SW of Garden City, Texas',
   'time': 1784242641888,
   'updated': 1784299975893,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/tx2026nxnzkm',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=tx2026nxnzkm&format=geojson',
   'felt': 1,
   'cdi': 2.2,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 168,
   'net': 'tx',
   'code': '2026nxnzkm',
   'ids': ',us7000t16i,tx2026nxnzkm,',
   'sources': ',us,tx,',
   'types': ',dyfi,origin,phase-data,',
   'nst': 47,
   'dmin': 0.1,
   'rms': 0.1,
   'gap': 87,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 3.3 - 24 km SW of Garden City, Texas'},
  'geometry': {'type': 'Point', 'coordinates': [-101.683, 31.725, 7.1289]},
  'id': 'tx2026nxnzkm'},
 {'type': 'Feature',
  'properties': {'mag': 0.88,
   'place': '12 km S of Anza, CA',
   'time': 1784242627980,
   'updated': 1784302555420,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci40656794',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=ci40656794&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 12,
   'net': 'ci',
   'code': '40656794',
   'ids': ',ci40656794,',
   'sources': ',ci,',
   'types': ',focal-mechanism,nearby-cities,origin,phase-data,',
   'nst': 33,
   'dmin': 0.06643,
   'rms': 0.17,
   'gap': 60,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.9 - 12 km S of Anza, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-116.661833333333, 33.4506666666667, 3.95]},
  'id': 'ci40656794'},
 {'type': 'Feature',
  'properties': {'mag': 0.86,
   'place': '18 km E of Little Lake, CA',
   'time': 1784242571350,
   'updated': 1784313115045,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci40656786',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=ci40656786&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 11,
   'net': 'ci',
   'code': '40656786',
   'ids': ',ci40656786,',
   'sources': ',ci,',
   'types': ',nearby-cities,origin,phase-data,',
   'nst': 19,
   'dmin': 0.05795,
   'rms': 0.11,
   'gap': 82,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.9 - 18 km E of Little Lake, CA'},
  'geometry': {'type': 'Point', 'coordinates': [-117.7065, 35.912, 6.15]},
  'id': 'ci40656786'},
 {'type': 'Feature',
  'properties': {'mag': 2.25,
   'place': '6 km W of Cobb, CA',
   'time': 1784242298180,
   'updated': 1784247740195,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc75397371',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc75397371&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 78,
   'net': 'nc',
   'code': '75397371',
   'ids': ',nc75397371,',
   'sources': ',nc,',
   'types': ',focal-mechanism,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 48,
   'dmin': 0.006767,
   'rms': 0.1,
   'gap': 40,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 2.3 - 6 km W of Cobb, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.789497375488, 38.8316650390625, 1.76999998092651]},
  'id': 'nc75397371'},
 {'type': 'Feature',
  'properties': {'mag': 1.27,
   'place': '155 km W of Adak, Alaska',
   'time': 1784242242540,
   'updated': 1784331403250,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/av94313458',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=av94313458&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 25,
   'net': 'av',
   'code': '94313458',
   'ids': ',av94313458,',
   'sources': ',av,',
   'types': ',origin,phase-data,',
   'nst': 5,
   'dmin': 0.01968,
   'rms': 0.07,
   'gap': 288,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.3 - 155 km W of Adak, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-178.8805, 51.7905, 4.86]},
  'id': 'av94313458'},
 {'type': 'Feature',
  'properties': {'mag': 1.23,
   'place': '10 km WNW of Cobb, CA',
   'time': 1784241944350,
   'updated': 1784246843098,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc75397361',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc75397361&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 23,
   'net': 'nc',
   'code': '75397361',
   'ids': ',nc75397361,',
   'sources': ',nc,',
   'types': ',nearby-cities,origin,phase-data,scitech-link,',
   'nst': 15,
   'dmin': 0.008423,
   'rms': 0.03,
   'gap': 109,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 1.2 - 10 km WNW of Cobb, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.833168029785, 38.8511657714844, 0.660000026226044]},
  'id': 'nc75397361'},
 {'type': 'Feature',
  'properties': {'mag': 0.72,
   'place': '10 km WNW of Cobb, CA',
   'time': 1784241897210,
   'updated': 1784241995437,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc75397356',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc75397356&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 8,
   'net': 'nc',
   'code': '75397356',
   'ids': ',nc75397356,',
   'sources': ',nc,',
   'types': ',nearby-cities,origin,phase-data,',
   'nst': 8,
   'dmin': 0.007003,
   'rms': 0.01,
   'gap': 106,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 0.7 - 10 km WNW of Cobb, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.831001281738, 38.851001739502, 0.920000016689301]},
  'id': 'nc75397356'},
 {'type': 'Feature',
  'properties': {'mag': 1.7,
   'place': '61 km SW of Adak, Alaska',
   'time': 1784241855083,
   'updated': 1784273837784,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/aka2026nztuhl',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=aka2026nztuhl&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 44,
   'net': 'ak',
   'code': 'a2026nztuhl',
   'ids': ',aka2026nztuhl,',
   'sources': ',ak,',
   'types': ',origin,phase-data,',
   'nst': 11,
   'dmin': 0.3,
   'rms': 0.3,
   'gap': 259,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.7 - 61 km SW of Adak, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-177.18, 51.436, 15.7]},
  'id': 'aka2026nztuhl'},
 {'type': 'Feature',
  'properties': {'mag': 1.32,
   'place': '3 km WSW of Tsawwassen, Canada',
   'time': 1784241674650,
   'updated': 1784307330390,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/uw714054021',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=uw714054021&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 27,
   'net': 'uw',
   'code': '714054021',
   'ids': ',uw714054021,',
   'sources': ',uw,',
   'types': ',origin,phase-data,',
   'nst': 10,
   'dmin': 0.259,
   'rms': 0.07,
   'gap': 251,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.3 - 3 km WSW of Tsawwassen, Canada'},
  'geometry': {'type': 'Point',
   'coordinates': [-123.1265, 49.0048333333333, 17.2]},
  'id': 'uw714054021'},
 {'type': 'Feature',
  'properties': {'mag': 0.94,
   'place': '2 km N of The Geysers, CA',
   'time': 1784240929790,
   'updated': 1784241025468,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc75397351',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc75397351&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 14,
   'net': 'nc',
   'code': '75397351',
   'ids': ',nc75397351,',
   'sources': ',nc,',
   'types': ',nearby-cities,origin,phase-data,',
   'nst': 8,
   'dmin': 0.007263,
   'rms': 0.01,
   'gap': 152,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 0.9 - 2 km N of The Geysers, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.75333404541, 38.7953338623047, 0.860000014305115]},
  'id': 'nc75397351'},
 {'type': 'Feature',
  'properties': {'mag': 1.9,
   'place': '21 km SSW of Point Possession, Alaska',
   'time': 1784240812184,
   'updated': 1784273731364,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/aka2026nztffe',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=aka2026nztffe&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 56,
   'net': 'ak',
   'code': 'a2026nztffe',
   'ids': ',aka2026nztffe,',
   'sources': ',ak,',
   'types': ',origin,phase-data,',
   'nst': 39,
   'dmin': 0.4,
   'rms': 0.6,
   'gap': 44,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.9 - 21 km SSW of Point Possession, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-150.856, 60.751, 48.4]},
  'id': 'aka2026nztffe'},
 {'type': 'Feature',
  'properties': {'mag': 1.16,
   'place': '1 km ESE of McMillin, Washington',
   'time': 1784240493380,
   'updated': 1784241783240,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/uw714054001',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=uw714054001&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 21,
   'net': 'uw',
   'code': '714054001',
   'ids': ',uw714054001,',
   'sources': ',uw,',
   'types': ',origin,phase-data,',
   'nst': 20,
   'dmin': 0.1917,
   'rms': 0.52,
   'gap': 307,
   'magType': 'ml',
   'type': 'explosion',
   'title': 'M 1.2 Explosion - 1 km ESE of McMillin, Washington'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.213333333333, 47.1325, -0.69]},
  'id': 'uw714054001'},
 {'type': 'Feature',
  'properties': {'mag': 4.4,
   'place': '58 km SE of Lata, Solomon Islands',
   'time': 1784240293508,
   'updated': 1784241917040,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000t167',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000t167&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 298,
   'net': 'us',
   'code': '7000t167',
   'ids': ',us7000t167,',
   'sources': ',us,',
   'types': ',origin,phase-data,',
   'nst': 35,
   'dmin': 9.588,
   'rms': 0.75,
   'gap': 64,
   'magType': 'mb',
   'type': 'earthquake',
   'title': 'M 4.4 - 58 km SE of Lata, Solomon Islands'},
  'geometry': {'type': 'Point', 'coordinates': [166.1885, -11.084, 198.962]},
  'id': 'us7000t167'},
 {'type': 'Feature',
  'properties': {'mag': -0.12,
   'place': '89 km SSE of Kokhanok, Alaska',
   'time': 1784239457960,
   'updated': 1784332065420,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/av93064499',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=av93064499&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 0,
   'net': 'av',
   'code': '93064499',
   'ids': ',av93064499,',
   'sources': ',av,',
   'types': ',origin,phase-data,',
   'nst': 7,
   'dmin': 0.07098,
   'rms': 0.22,
   'gap': 248,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M -0.1 - 89 km SSE of Kokhanok, Alaska'},
  'geometry': {'type': 'Point',
   'coordinates': [-154.401166666667, 58.6615, 9.05]},
  'id': 'av93064499'},
 {'type': 'Feature',
  'properties': {'mag': 0.73,
   'place': '7 km NW of The Geysers, CA',
   'time': 1784239389740,
   'updated': 1784239485864,
   'tz': None,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc75397331',
   'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=nc75397331&format=geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 8,
   'net': 'nc',
   'code': '75397331',
   'ids': ',nc75397331,',
   'sources': ',nc,',
   'types': ',nearby-cities,origin,phase-data,',
   'nst': 7,
   'dmin': 0.004335,
   'rms': 0.01,
   'gap': 83,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 0.7 - 7 km NW of The Geysers, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.814666748047, 38.8258323669434, 2.15000009536743]},
  'id': 'nc75397331'},
 {'type': 'Feature',
  'properties': {'mag': 2.1,
   'place': '130 km WSW of Adak, Alaska',

In [67]:
type(earthquake_json['features'])

list

In [68]:
earthquake_json['features'][0]

{'type': 'Feature',
 'properties': {'mag': 0.94,
  'place': '155 km W of Adak, Alaska',
  'time': 1784246163010,
  'updated': 1784331915180,
  'tz': None,
  'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/av94313543',
  'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=av94313543&format=geojson',
  'felt': None,
  'cdi': None,
  'mmi': None,
  'alert': None,
  'status': 'reviewed',
  'tsunami': 0,
  'sig': 14,
  'net': 'av',
  'code': '94313543',
  'ids': ',av94313543,',
  'sources': ',av,',
  'types': ',origin,phase-data,',
  'nst': 0,
  'dmin': 0.02037,
  'rms': 0.07,
  'gap': 290,
  'magType': 'ml',
  'type': 'earthquake',
  'title': 'M 0.9 - 155 km W of Adak, Alaska'},
 'geometry': {'type': 'Point',
  'coordinates': [-178.882166666667, 51.7903333333333, 0]},
 'id': 'av94313543'}

In [69]:
earthquake_properties_data = [
    quake['properties'] 
    for quake in earthquake_json['features']
]

In [71]:
df = pd.DataFrame(earthquake_properties_data)

df.head()

,mag,place,time,updated,tz,url,detail,felt,cdi,mmi,...,ids,sources,types,nst,dmin,rms,gap,magType,type,title
0,0.94,"155 km W of Adak, Alaska",1784246163010,1784331915180,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,...,",av94313543,",",av,",",origin,phase-data,",0.0,0.02037,0.07,290.0,ml,earthquake,"M 0.9 - 155 km W of Adak, Alaska"
1,1.80,"19 km WSW of Anchor Point, Alaska",1784245212327,1784274027912,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,...,",aka2026nzvqud,",",ak,",",origin,phase-data,",29.0,0.50000,0.60,75.0,ml,earthquake,"M 1.8 - 19 km WSW of Anchor Point, Alaska"
2,4.40,south of the Fiji Islands,1784244929037,1784246052040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,...,",us7000t16p,",",us,",",origin,phase-data,",51.0,5.72300,0.97,103.0,mb,earthquake,M 4.4 - south of the Fiji Islands
3,1.69,"24 km NE of San Ardo, CA",1784244709490,1784249247367,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,...,",nc75397381,",",nc,",",nearby-cities,origin,phase-data,scitech-link,",6.0,0.29510,0.34,175.0,md,earthquake,"M 1.7 - 24 km NE of San Ardo, CA"
4,0.81,"6 km WNW of Little Lake, CA",1784244496200,1784316465386,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,...,",ci40656810,",",ci,",",nearby-cities,origin,phase-data,",17.0,0.08760,0.10,82.0,ml,earthquake,"M 0.8 - 6 km WNW of Little Lake, CA"

# **Inspecting a DataFrame object**

In [3]:
df = pd.read_csv('../Datasets/earthquakes.csv')

## **Examining the data**

In [73]:
df.empty

False

In [74]:
df.shape

(9332, 26)

In [75]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [76]:
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...

In [77]:
df.tail(3)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.45260,NaN,276.0,",pr2018261000,",2.40,md,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01865,NaN,61.0,",ci38063959,",1.10,ml,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01698,NaN,39.0,",ci38063935,",0.66,ml,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

> **Tip :** By default, when we print dataframes with many columns in a Jupyter Notebook, only a subset of them will be displayed. This is because pandas has a limit on the number of columns it will show. We can modify this behavior using pd.set_option('display.max_columns', <new_value>). Consult the documentation at https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html for additional information. The notebook also contains a few example commands.

In [78]:
df.dtypes

alert       object
cdi        float64
code        object
detail      object
dmin       float64
felt       float64
gap        float64
ids         object
mag        float64
magType     object
mmi        float64
net         object
nst        float64
place       object
rms        float64
sig          int64
sources     object
status      object
time         int64
title       object
tsunami      int64
type        object
types       object
tz         float64
updated      int64
url         object
dtype: object

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9332 entries, 0 to 9331
Data columns (total 26 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   alert    59 non-null     object
 1   cdi      329 non-null    float64
 2   code     9332 non-null   object
 3   detail   9332 non-null   object
 4   dmin     6139 non-null   float64
 5   felt     329 non-null    float64
 6   gap      6164 non-null   float64
 7   ids      9332 non-null   object
 8   mag      9331 non-null   float64
 9   magType  9331 non-null   object
 10  mmi      93 non-null     float64
 11  net      9332 non-null   object
 12  nst      5364 non-null   float64
 13  place    9332 non-null   object
 14  rms      9332 non-null   float64
 15  sig      9332 non-null   int64
 16  sources  9332 non-null   object
 17  status   9332 non-null   object
 18  time     9332 non-null   int64
 19  title    9332 non-null   object
 20  tsunami  9332 non-null   int64
 21  type     9332 non-null   object
 22  types    9332 non-null   object
 23  tz       9331 non-null   float64
 24  updated  9332 non-null   int64
 25  url      9332 non-null   object
dtypes: float64(9), int64(4), object(13)
memory usage: 1.9+ MB

## **Describing and summarizing the data**

In [80]:
df.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,329.000000,6139.000000,329.000000,6164.000000,9331.000000,93.000000,5364.000000,9332.000000,9332.000000,9.332000e+03,9332.000000,9331.000000,9.332000e+03
mean,2.754711,0.544925,12.310030,121.506588,1.497345,3.651398,19.053878,0.362122,56.899914,1.538284e+12,0.006537,-451.990140,1.538537e+12
std,1.010637,2.214305,48.954944,72.962363,1.203347,1.790523,15.492315,0.317784,91.872163,6.080306e+08,0.080589,231.752571,6.564135e+08
min,0.000000,0.000648,0.000000,12.000000,-1.260000,0.000000,0.000000,0.000000,0.000000,1.537229e+12,0.000000,-720.000000,1.537230e+12
25%,2.000000,0.020425,1.000000,66.142500,0.720000,2.680000,8.000000,0.119675,8.000000,1.537793e+12,0.000000,-540.000000,1.537996e+12
50%,2.700000,0.059050,2.000000,105.000000,1.300000,3.720000,15.000000,0.210000,26.000000,1.538245e+12,0.000000,-480.000000,1.538621e+12
75%,3.300000,0.177250,5.000000,159.000000,1.900000,4.570000,25.000000,0.590000,56.000000,1.538766e+12,0.000000,-480.000000,1.539110e+12
max,8.400000,53.737000,580.000000,355.910000,7.500000,9.120000,172.000000,1.910000,2015.000000,1.539475e+12,1.000000,720.000000,1.539537e+12

> **Tip :** If we want different percentiles, we can pass them in with the percentiles argument. For example, if we wanted only the 5th and 95th percentiles, we would run df.describe(percentiles=[0.05, 0.95]). Note we will still get the 50th percentile back because that is the median.

In [82]:
df.describe(include=object)

,alert,code,detail,ids,magType,net,place,sources,status,title,type,types,url
count,59,9332,9332,9332,9331,9332,9332,9332,9332,9332,9332,9332,9332
unique,2,9332,9332,9332,10,14,5433,52,2,7807,5,42,9332
top,green,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,",ci37389218,",ml,ak,"10km NE of Aguanga, CA",",ak,",reviewed,"M 0.4 - 10km NE of Aguanga, CA",earthquake,",geoserve,origin,phase-data,",https://earthquake.usgs.gov/earthquakes/eventp...
freq,58,1,1,1,6803,3166,306,2981,7797,55,9081,5301,1

![Helpful calculation methods for series and dataframes](../Images/Helpful_calculation_methods_for_series_and_dataframes.png)

- With Series objects, we have some additional methods for describing our data:
    - **unique():** Returns the distinct values of the column.
    - **value_counts():** Returns a frequency table of the number of times each unique value in a given column appears, or, alternatively, the percentage of times each unique value appears when passed **normalize = True**.
    - **mode():** Returns the most common value of the column.

In [83]:
df['alert'].unique()

array([nan, 'green', 'red'], dtype=object)

In [84]:
df['alert'].value_counts()

alert
green    58
red       1
Name: count, dtype: int64

![Helpful methods for the index](../Images/Helpful_methods_for_the_index.png)

# **Grabbing subsets of the data**

In [2]:
df = pd.read_csv('../Datasets/earthquakes.csv')

df.empty

False

## **Selecting columns**

In [3]:
df.mag

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

In [4]:
df['mag']

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

> **Tip :** We can also select columns using the get() method. This has the benefits of not raising an error if the column doesn't exist and allowing us to provide a backup value—the default is None. For example, if we call df.get('event', False), it will return False since we don't have an event column.

In [5]:
df[['mag', 'title']]

       mag                                     title
0     1.35             M 1.4 - 9km NE of Aguanga, CA
1     1.29             M 1.3 - 9km NE of Aguanga, CA
2     3.42             M 3.4 - 8km NE of Aguanga, CA
3     0.44             M 0.4 - 9km NE of Aguanga, CA
4     2.16             M 2.2 - 10km NW of Avenal, CA
...    ...                                       ...
9327  0.62      M 0.6 - 9km ENE of Mammoth Lakes, CA
9328  1.00               M 1.0 - 3km W of Julian, CA
9329  2.40  M 2.4 - 35km NNE of Hatillo, Puerto Rico
9330  1.10             M 1.1 - 9km NE of Aguanga, CA
9331  0.66             M 0.7 - 9km NE of Aguanga, CA

[9332 rows x 2 columns]

In [6]:
df[
    ['title', 'time'] 
    + [col for col in df.columns if col.startswith('mag')]
]

                                         title           time   mag magType
0                M 1.4 - 9km NE of Aguanga, CA  1539475168010  1.35      ml
1                M 1.3 - 9km NE of Aguanga, CA  1539475129610  1.29      ml
2                M 3.4 - 8km NE of Aguanga, CA  1539475062610  3.42      ml
3                M 0.4 - 9km NE of Aguanga, CA  1539474978070  0.44      ml
4                M 2.2 - 10km NW of Avenal, CA  1539474716050  2.16      md
...                                        ...            ...   ...     ...
9327      M 0.6 - 9km ENE of Mammoth Lakes, CA  1537230228060  0.62      md
9328               M 1.0 - 3km W of Julian, CA  1537230135130  1.00      ml
9329  M 2.4 - 35km NNE of Hatillo, Puerto Rico  1537229908180  2.40      md
9330             M 1.1 - 9km NE of Aguanga, CA  1537229545350  1.10      ml
9331             M 0.7 - 9km NE of Aguanga, CA  1537228864470  0.66      ml

[9332 rows x 4 columns]

## **Slicing**

In [8]:
df[100:103]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
100,NaN,NaN,20280310,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20280310,",1.20,ml,...,",ak,",automatic,1539435449480,"M 1.2 - 25km NW of Ester, Alaska",0,earthquake,",geoserve,origin,",-540.0,1539443551010,https://earthquake.usgs.gov/earthquakes/eventp...
101,NaN,NaN,73096756,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01355,NaN,185.0,",nc73096756,",0.59,md,...,",nc,",automatic,1539435391320,"M 0.6 - 8km ESE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539439802162,https://earthquake.usgs.gov/earthquakes/eventp...
102,NaN,NaN,37388730,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.02987,NaN,39.0,",ci37388730,",1.33,ml,...,",ci,",automatic,1539435293090,"M 1.3 - 8km ENE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1539435940470,https://earthquake.usgs.gov/earthquakes/eventp...

In [9]:
df[['title', 'time']][100:103]

                                    title           time
100      M 1.2 - 25km NW of Ester, Alaska  1539435449480
101  M 0.6 - 8km ESE of Mammoth Lakes, CA  1539435391320
102        M 1.3 - 8km ENE of Aguanga, CA  1539435293090

In [10]:
df[100:103][['title', 'time']].equals(
    df[['title', 'time']][100:103]
)

True

In [11]:
df[100:103]['title'] = df[100:103]['title'].str.lower()

/tmp/ipykernel_4222/502563613.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[100:103]['title'] = df[100:103]['title'].str.lower()
/tmp/ipykernel_4222/502563613.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[100:103]['title'] = df[100:103]['title'].str.lower()

In [13]:
df[100:103]['title']

100        M 1.2 - 25km NW of Ester, Alaska
101    M 0.6 - 8km ESE of Mammoth Lakes, CA
102          M 1.3 - 8km ENE of Aguanga, CA
Name: title, dtype: object

## **Indexing**

In [14]:
df.loc[100:102, 'title'] = df.loc[100:102, 'title'].str.lower()

In [18]:
df.loc[100:102, 'title'] # end index is inclusive

100        m 1.2 - 25km nw of ester, alaska
101    m 0.6 - 8km ese of mammoth lakes, ca
102          m 1.3 - 8km ene of aguanga, ca
Name: title, dtype: object

In [16]:
df.loc[:, 'title']

0                  M 1.4 - 9km NE of Aguanga, CA
1                  M 1.3 - 9km NE of Aguanga, CA
2                  M 3.4 - 8km NE of Aguanga, CA
3                  M 0.4 - 9km NE of Aguanga, CA
4                  M 2.2 - 10km NW of Avenal, CA
                          ...
9327        M 0.6 - 9km ENE of Mammoth Lakes, CA
9328                 M 1.0 - 3km W of Julian, CA
9329    M 2.4 - 35km NNE of Hatillo, Puerto Rico
9330               M 1.1 - 9km NE of Aguanga, CA
9331               M 0.7 - 9km NE of Aguanga, CA
Name: title, Length: 9332, dtype: object

In [17]:
df.loc[10:15, ['title', 'mag']]

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13
15       M 2.0 - 156km WNW of Haines Junction, Canada  2.00

In [21]:
df.iloc[10:15, [19, 8]] # end index is exclusive

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13

In [22]:
df.iloc[10:15, 6:10]

      gap             ids   mag magType
10   57.0    ,ci37389162,  0.50      ml
11  186.0  ,pr2018286010,  2.77      md
12   76.0    ,ci37389146,  0.50      ml
13  157.0    ,us1000hbti,  4.50      mb
14   71.0    ,nc73096921,  2.13      md

In [24]:
df.iloc[10:15, 6:10].equals(df.loc[10:14, 'gap':'magType'])

True

In [25]:
df.at[10, 'mag']

np.float64(0.5)

In [26]:
df.iat[10, 8]

np.float64(0.5)

## **Filtering**

In [27]:
# Boolean Mask
df['mag'] > 2

0       False
1       False
2        True
3       False
4        True
        ...
9327    False
9328    False
9329     True
9330    False
9331    False
Name: mag, Length: 9332, dtype: bool

In [28]:
df[df['mag'] >= 7.0]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
837,green,4.1,1000haa3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.763,3.0,14.0,",us1000haa3,pt18283003,at00pgehsk,",7.0,mww,...,",us,pt,at,",reviewed,1539204500290,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",600.0,1539378744253,https://earthquake.usgs.gov/earthquakes/eventp...
5263,red,8.4,1000h3p4,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.589,18.0,27.0,",us1000h3p4,us1000h4p4,",7.5,mww,...,",us,us,",reviewed,1538128963480,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",480.0,1539123134531,https://earthquake.usgs.gov/earthquakes/eventp...

In [30]:
df[df['mag'] >= 7.0][['alert', 'mag', 'magType', 'title', 'tsunami', 'type']]

,alert,mag,magType,title,tsunami,type
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [31]:
df.loc[
    df['mag'] >= 7.0,
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [32]:
df.loc[
    (df['tsunami'] == 1) & (df['alert'] == 'red'),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [33]:
df.loc[
    (df['tsunami'] == 1) | (df['alert'] == 'red'),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
36,NaN,5.0,mww,"M 5.0 - 165km NNW of Flying Fish Cove, Christm...",1,earthquake
118,green,6.7,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
501,green,5.6,mww,"M 5.6 - 128km SE of Kimbe, Papua New Guinea",1,earthquake
799,green,6.5,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
816,green,6.2,mww,"M 6.2 - 94km SW of Kokopo, Papua New Guinea",1,earthquake
...,...,...,...,...,...,...
8561,NaN,5.4,mb,"M 5.4 - 228km S of Taron, Papua New Guinea",1,earthquake
8624,NaN,5.1,mb,"M 5.1 - 278km SE of Pondaguitan, Philippines",1,earthquake
9133,green,5.1,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake
9175,NaN,5.2,mb,"M 5.2 - 126km N of Dili, East Timor",1,earthquake
9304,NaN,5.1,mb,"M 5.1 - 34km NW of Finschhafen, Papua New Guinea",1,earthquake

> **Important note :** When creating Boolean masks, we must use bitwise operators (&, |, ~) instead of logical operators (and, or, not). A good way to remember this is that we want a Boolean for each item in the series we are testing rather than a single Boolean. For example, with the earthquake data, if we want to select the rows where the magnitude is greater than 1.5, then we want one Boolean value for each row, indicating whether the row should be selected. In cases where we want a single value for the data, perhaps to summarize it, we can use any()/ all() to condense a Boolean series into a single Boolean value that can be used with logical operators.

In [34]:
df.loc[
    (df['place'].str.contains('Alaska')) & (df['alert'].notnull()),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
1015,green,5.0,ml,"M 5.0 - 61km SSW of Chignik Lake, Alaska",1,earthquake
1273,green,4.0,ml,"M 4.0 - 71km SW of Kaktovik, Alaska",1,earthquake
1795,green,4.0,ml,"M 4.0 - 60km WNW of Valdez, Alaska",1,earthquake
2752,green,4.0,ml,"M 4.0 - 67km SSW of Kaktovik, Alaska",1,earthquake
3260,green,3.9,ml,"M 3.9 - 44km N of North Nenana, Alaska",0,earthquake
4101,green,4.2,ml,"M 4.2 - 131km NNW of Arctic Village, Alaska",0,earthquake
6897,green,3.8,ml,"M 3.8 - 80km SSW of Kaktovik, Alaska",0,earthquake
8524,green,3.8,ml,"M 3.8 - 69km SSW of Kaktovik, Alaska",0,earthquake
9133,green,5.1,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake

> **Tip :** We can use the bitwise negation operator (~), also called NOT, to negate all the Boolean values, which makes all True values False and vice versa. So, `df.alert.notnull() and ~df.alert.isnull()` are equivalent.

In [35]:
df.loc[
    (df['place'].str.contains(r'CA|California$')) & (df['mag'] > 3.8),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
1465,green,3.83,mw,"M 3.8 - 109km WNW of Trinidad, CA",0,earthquake
2414,green,3.83,mw,"M 3.8 - 5km SW of Tres Pinos, CA",1,earthquake

> **Tip :** Regular expressions are extremely powerful, but unfortunately, also difficult to get right. It is often helpful to grab some sample lines for parsing and use a website to test them. Note that regular expressions come in many flavors, so be sure to select Python. This website supports Python flavor regular expressions, and also provides a nice cheat sheet on the side: https://regex101.com/.

In [40]:
df.loc[
    df['mag'].between(6.5, 7.5), # by defulat inclusive=True
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
118,green,6.7,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
799,green,6.5,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
4363,green,6.7,mww,"M 6.7 - 263km NNE of Ndoi Island, Fiji",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [41]:
df.loc[
    df['magType'].isin(['mw', 'mwb']),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
995,NaN,3.35,mw,"M 3.4 - 9km WNW of Cobb, CA",0,earthquake
1465,green,3.83,mw,"M 3.8 - 109km WNW of Trinidad, CA",0,earthquake
2414,green,3.83,mw,"M 3.8 - 5km SW of Tres Pinos, CA",1,earthquake
4988,green,4.41,mw,"M 4.4 - 1km SE of Delta, B.C., MX",1,earthquake
6307,green,5.80,mwb,"M 5.8 - 297km NNE of Ndoi Island, Fiji",0,earthquake
8257,green,5.70,mwb,"M 5.7 - 175km SSE of Lambasa, Fiji",0,earthquake

In [43]:
df['mag'][df['mag'].idxmin()], df['mag'][df['mag'].idxmax()]

(np.float64(-1.26), np.float64(7.5))

In [45]:
df.loc[
    [df['mag'].idxmin(), df['mag'].idxmax()],
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
2409,NaN,-1.26,ml,"M -1.3 - 41km ENE of Adak, Alaska",0,earthquake
5263,red,7.50,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

> **Important note :** Be advised that the `filter()` method does not filter the data according to its values, as we did in this section; rather, it can be used to subset rows or columns based on their names.

# **Adding and removing data**

In [5]:
df_copy = df.copy()

df_copy.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...

> **Important note :** By default, `df.copy()` makes a deep copy of the dataframe, which allows us to make changes to either the copy or the original without repercussions. If we pass in `deep=False`, we can obtain a shallow copy changes to the shallow copy affect the original and vice versa. We will almost always want the deep copy, since we can change it without affecting the original.

In [6]:
df = pd.read_csv(
    '../Datasets/earthquakes.csv', 
    usecols= [
        'time', 'title', 'place', 'magType', 'mag', 'alert', 'tsunami'
    ]
)

df.head()

,alert,mag,magType,place,time,title,tsunami
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0

## **Creating new data**

In [7]:
df['source'] = 'USGS API'

df.head()

,alert,mag,magType,place,time,title,tsunami,source
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,USGS API
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,USGS API
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,USGS API

> **Important note :** We cannot create the column with attribute notation (df.source) because the dataframe doesn't have that attribute yet, so we must use dictionary notation `(df['source'])`.

In [9]:
df['mag_negative'] = df['mag'] < 0

df.head()

,alert,mag,magType,place,time,title,tsunami,source,mag_negative
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,USGS API,False
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,USGS API,False
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,USGS API,False

In [14]:
df['place'].str.extract(r', (.*$)')[0].sort_values().unique()

array(['Afghanistan', 'Alaska', 'Argentina', 'Arizona', 'Arkansas',
       'Australia', 'Azerbaijan', 'B.C., MX', 'Barbuda', 'Bolivia',
       'Bonaire, Saint Eustatius and Saba ', 'British Virgin Islands',
       'Burma', 'CA', 'California', 'Canada', 'Chile', 'China',
       'Christmas Island', 'Colombia', 'Colorado', 'Costa Rica',
       'Dominican Republic', 'East Timor', 'Ecuador', 'Ecuador region',
       'El Salvador', 'Fiji', 'Greece', 'Greenland', 'Guam', 'Guatemala',
       'Haiti', 'Hawaii', 'Honduras', 'Idaho', 'Illinois', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Italy', 'Jamaica', 'Japan', 'Kansas',
       'Kentucky', 'Kyrgyzstan', 'Martinique', 'Mauritius', 'Mayotte',
       'Mexico', 'Missouri', 'Montana', 'NV', 'Nevada', 'New Caledonia',
       'New Hampshire', 'New Mexico', 'New Zealand', 'Nicaragua',
       'North Carolina', 'Northern Mariana Islands', 'Oklahoma', 'Oregon',
       'Pakistan', 'Papua New Guinea', 'Peru', 'Philippines',
       'Puerto Rico', 'Romania', 'Russia', 'Saint Helena',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Carolina',
       'South Georgia and the South Sandwich Islands',
       'South Sandwich Islands', 'Taiwan', 'Tajikistan', 'Tennessee',
       'Texas', 'Tonga', 'Turkey', 'U.S. Virgin Islands', 'Utah',
       'Uzbekistan', 'Vanuatu', 'Vermont', 'Washington', 'Wyoming',
       'Yemen', nan], dtype=object)

In [15]:
df['parsed_place'] = df['place'].str.replace(
    r'.* of ', '', regex=True # remove <x> of <x>
).str.replace(
    'the ', '' # remove "the "
).str.replace(
    r'CA$', 'California', regex=True # fix California
).str.replace(
    r'NV$', 'Nevada', regex=True # fix Nevada
).str.replace(
    r'MX$', 'Mexico', regex=True # fix Mexico
).str.replace(
    r' region$', '', regex=True # fix " region" endings
).str.replace(
    'northern ', '' # remove "northern "
).str.replace(
    'Fiji Islands', 'Fiji' # line up the Fiji places
).str.replace( # remove anything else extraneous from start 
    r'^.*, ', '', regex=True).str.strip() # remove any extra spaces

df.head()

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False,California
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False,California
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,USGS API,False,California
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,USGS API,False,California
4,NaN,2.16,md,"10km NW of Avenal, CA",1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,USGS API,False,California

In [18]:
df['parsed_place'].sort_values().unique()

array(['Afghanistan', 'Alaska', 'Argentina', 'Arizona', 'Arkansas',
       'Ascension Island', 'Australia', 'Azerbaijan', 'Balleny Islands',
       'Barbuda', 'Bolivia', 'British Virgin Islands', 'Burma',
       'California', 'Canada', 'Carlsberg Ridge',
       'Central East Pacific Rise', 'Central Mid-Atlantic Ridge', 'Chile',
       'China', 'Christmas Island', 'Colombia', 'Colorado', 'Costa Rica',
       'Dominican Republic', 'East Timor', 'Ecuador', 'El Salvador',
       'Fiji', 'Greece', 'Greenland', 'Guam', 'Guatemala', 'Haiti',
       'Hawaii', 'Honduras', 'Idaho', 'Illinois', 'India',
       'Indian Ocean Triple Junction', 'Indonesia', 'Iran', 'Iraq',
       'Italy', 'Jamaica', 'Japan', 'Kansas', 'Kentucky',
       'Kermadec Islands', 'Kuril Islands', 'Kyrgyzstan', 'Martinique',
       'Mauritius', 'Mayotte', 'Mexico', 'Mid-Indian Ridge', 'Missouri',
       'Montana', 'Nevada', 'New Caledonia', 'New Hampshire',
       'New Mexico', 'New Zealand', 'Nicaragua', 'North Carolina',
       'Northern East Pacific Rise', 'Northern Mariana Islands',
       'Northern Mid-Atlantic Ridge', 'Oklahoma', 'Oregon',
       'Pacific-Antarctic Ridge', 'Pakistan', 'Papua New Guinea', 'Peru',
       'Philippines', 'Prince Edward Islands', 'Puerto Rico',
       'Queen Charlotte Islands', 'Romania', 'Russia',
       'Saint Eustatius and Saba', 'Saint Helena', 'Socotra',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Carolina',
       'South Georgia and South Sandwich Islands',
       'South Sandwich Islands', 'Southeast Indian Ridge',
       'Southern East Pacific Rise', 'Southern Mid-Atlantic Ridge',
       'Southwest Indian Ridge', 'Sumatra', 'Taiwan', 'Tajikistan',
       'Tennessee', 'Texas', 'Tonga', 'Turkey', 'U.S. Virgin Islands',
       'Utah', 'Uzbekistan', 'Vanuatu', 'Vermont', 'Washington',
       'Western Indian-Antarctic Ridge', 'Western Xizang', 'Wyoming',
       'Yemen'], dtype=object)

> I**mportant note :** In practice, entity recognition can be an extremely difficult problem, where
we may look to employ `natural language processing (NLP)` algorithms to help us. more information
can be found at https://www.kdnuggets.com/2018/12/introduction-named-entity-recognition.html.

In [21]:
# Creating multiple columns at time
df.assign( # return a new DataFram With these columns added
    in_ca = df['parsed_place'].str.endswith('California'),
    in_alaska = df['parsed_place'].str.endswith('Alaska')
).sample(5, random_state=0) # select a random subsets of n-elemnt and

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place,in_ca,in_alaska
7207,NaN,4.80,mwr,"73km SSW of Masachapa, Nicaragua",1537749595210,"M 4.8 - 73km SSW of Masachapa, Nicaragua",0,USGS API,False,Nicaragua,False,False
4755,NaN,1.09,ml,"28km NNW of Packwood, Washington",1538227540460,"M 1.1 - 28km NNW of Packwood, Washington",0,USGS API,False,Washington,False,False
4595,NaN,1.80,ml,"77km SSW of Kaktovik, Alaska",1538259609862,"M 1.8 - 77km SSW of Kaktovik, Alaska",0,USGS API,False,Alaska,False,True
3566,NaN,1.50,ml,"102km NW of Arctic Village, Alaska",1538464751822,"M 1.5 - 102km NW of Arctic Village, Alaska",0,USGS API,False,Alaska,False,True
2182,NaN,0.90,ml,"26km ENE of Pine Valley, CA",1538801713880,"M 0.9 - 26km ENE of Pine Valley, CA",0,USGS API,False,California,True,False

In [22]:
# Using assign with labda function wich accept DataFrame in argument in form x Variable
df.assign(
    in_ca = df['parsed_place'] == 'California',
    in_alaska = df['parsed_place'] == 'Alaska',
    neither = lambda x : ~x.in_ca & ~x.in_alaska
).sample(5, random_state=0)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place,in_ca,in_alaska,neither
7207,NaN,4.80,mwr,"73km SSW of Masachapa, Nicaragua",1537749595210,"M 4.8 - 73km SSW of Masachapa, Nicaragua",0,USGS API,False,Nicaragua,False,False,True
4755,NaN,1.09,ml,"28km NNW of Packwood, Washington",1538227540460,"M 1.1 - 28km NNW of Packwood, Washington",0,USGS API,False,Washington,False,False,True
4595,NaN,1.80,ml,"77km SSW of Kaktovik, Alaska",1538259609862,"M 1.8 - 77km SSW of Kaktovik, Alaska",0,USGS API,False,Alaska,False,True,False
3566,NaN,1.50,ml,"102km NW of Arctic Village, Alaska",1538464751822,"M 1.5 - 102km NW of Arctic Village, Alaska",0,USGS API,False,Alaska,False,True,False
2182,NaN,0.90,ml,"26km ENE of Pine Valley, CA",1538801713880,"M 0.9 - 26km ENE of Pine Valley, CA",0,USGS API,False,California,True,False,False

In [23]:
tsunami = df[df['tsunami'] == 1]
no_tsunami = df[df['tsunami'] == 0]

tsunami.shape, no_tsunami.shape

((61, 10), (9271, 10))

In [26]:
pd.concat([tsunami, no_tsunami]).shape # by Defualt axis = 0 append rows to the bottom of the dataframe

(9332, 10)

In [29]:
# df.append(no_tsunami).shape

In [30]:
additional_columns = pd.read_csv(
    '../Datasets/earthquakes.csv',
    usecols= ['tz', 'felt', 'ids']
)

df.shape

(9332, 10)

In [32]:
pd.concat(
    [df.head(2), additional_columns.head(2)], 
    axis=1 # Add Columns to the right of DataFrame
)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place,felt,ids,tz
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False,California,NaN,",ci37389218,",-480.0
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False,California,NaN,",ci37389202,",-480.0

In [34]:
additional_columns = pd.read_csv(
    '../Datasets/earthquakes.csv',
    usecols= ['tz', 'felt', 'ids', 'time'],
    index_col= 'time'
)

In [36]:
# concat function use index to align the column side by side 
pd.concat(
    [df.head(2), additional_columns.head(2)],
    axis=1
)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place,felt,ids,tz
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1.539475e+12,"M 1.4 - 9km NE of Aguanga, CA",0.0,USGS API,False,California,NaN,NaN,NaN
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1.539475e+12,"M 1.3 - 9km NE of Aguanga, CA",0.0,USGS API,False,California,NaN,NaN,NaN
1539475168010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",ci37389218,",-480.0
1539475129610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",ci37389202,",-480.0

> **Important note :** Often, we will use `concat()` or `append()` to add rows, but `merge()` or `join()` to add columns.

In [40]:
pd.concat(
    [
        tsunami.head(2), 
        no_tsunami.assign(type='earthquarke').head(2)
    ],
    join = 'inner' # By defualt is set to outer
)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place
36,NaN,5.00,mww,"165km NNW of Flying Fish Cove, Christmas Island",1539459504090,"M 5.0 - 165km NNW of Flying Fish Cove, Christm...",1,USGS API,False,Christmas Island
118,green,6.70,mww,"262km NW of Ozernovskiy, Russia",1539429023560,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,USGS API,False,Russia
0,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False,California
1,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False,California

In [41]:
pd.concat(
    [
        tsunami.head(2),
        no_tsunami.assign( type = 'earthquarke').head(2)
    ],
    join='inner',
    ignore_index=True
)

,alert,mag,magType,place,time,title,tsunami,source,mag_negative,parsed_place
0,NaN,5.00,mww,"165km NNW of Flying Fish Cove, Christmas Island",1539459504090,"M 5.0 - 165km NNW of Flying Fish Cove, Christm...",1,USGS API,False,Christmas Island
1,green,6.70,mww,"262km NW of Ozernovskiy, Russia",1539429023560,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,USGS API,False,Russia
2,NaN,1.35,ml,"9km NE of Aguanga, CA",1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,USGS API,False,California
3,NaN,1.29,ml,"9km NE of Aguanga, CA",1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,USGS API,False,California

## **Deleting unwanted data**

In [42]:
df.columns

Index(['alert', 'mag', 'magType', 'place', 'time', 'title', 'tsunami',
       'source', 'mag_negative', 'parsed_place'],
      dtype='object')

In [43]:
del df['source']

df.columns

Index(['alert', 'mag', 'magType', 'place', 'time', 'title', 'tsunami',
       'mag_negative', 'parsed_place'],
      dtype='object')

In [46]:
try:
    del df['source']
except KeyError as e:
    # raise KeyError("The key doen't exist anymore")
    print(e)

'source'

In [48]:
mag_negative = df.pop('mag_negative')

df.columns

Index(['alert', 'mag', 'magType', 'place', 'time', 'title', 'tsunami',
       'parsed_place'],
      dtype='object')

In [49]:
mag_negative.value_counts()

mag_negative
False    8841
True      491
Name: count, dtype: int64

In [50]:
df[mag_negative].head()

,alert,mag,magType,place,time,title,tsunami,parsed_place
39,NaN,-0.10,ml,"6km NW of Lemmon Valley, Nevada",1539458844506,"M -0.1 - 6km NW of Lemmon Valley, Nevada",0,Nevada
49,NaN,-0.10,ml,"6km NW of Lemmon Valley, Nevada",1539455017464,"M -0.1 - 6km NW of Lemmon Valley, Nevada",0,Nevada
135,NaN,-0.40,ml,"10km SSE of Beatty, Nevada",1539422175717,"M -0.4 - 10km SSE of Beatty, Nevada",0,Nevada
161,NaN,-0.02,md,"20km SSE of Ronan, Montana",1539412475360,"M -0.0 - 20km SSE of Ronan, Montana",0,Montana
198,NaN,-0.20,ml,"60km N of Pahrump, Nevada",1539398340822,"M -0.2 - 60km N of Pahrump, Nevada",0,Nevada

In [53]:
df.drop([0, 1]).head(2) # removing rows by indecies , return a new DataFrame Object

,alert,mag,magType,place,time,title,tsunami,parsed_place
2,NaN,3.42,ml,"8km NE of Aguanga, CA",1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,California
3,NaN,0.44,ml,"9km NE of Aguanga, CA",1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,California

In [54]:
cols_to_drop = [
    col for col in df.columns
    if col not in [
        'alert', 'mag', 'title', 'time', 'tsunami'
    ]
]

cols_to_drop

['magType', 'place', 'parsed_place']

In [56]:
df.drop(columns=cols_to_drop).head() # by defualt axis=0 rows

  alert   mag           time                          title  tsunami
0   NaN  1.35  1539475168010  M 1.4 - 9km NE of Aguanga, CA        0
1   NaN  1.29  1539475129610  M 1.3 - 9km NE of Aguanga, CA        0
2   NaN  3.42  1539475062610  M 3.4 - 8km NE of Aguanga, CA        0
3   NaN  0.44  1539474978070  M 0.4 - 9km NE of Aguanga, CA        0
4   NaN  2.16  1539474716050  M 2.2 - 10km NW of Avenal, CA        0

In [57]:
df.drop(
    columns=cols_to_drop
).equals(df.drop(cols_to_drop, axis=1))

True

In [58]:
df.drop(
    cols_to_drop, 
    axis=1, 
    inplace=True
)

df.head()

  alert   mag           time                          title  tsunami
0   NaN  1.35  1539475168010  M 1.4 - 9km NE of Aguanga, CA        0
1   NaN  1.29  1539475129610  M 1.3 - 9km NE of Aguanga, CA        0
2   NaN  3.42  1539475062610  M 3.4 - 8km NE of Aguanga, CA        0
3   NaN  0.44  1539474978070  M 0.4 - 9km NE of Aguanga, CA        0
4   NaN  2.16  1539474716050  M 2.2 - 10km NW of Avenal, CA        0

# **Further reading**

- Those with an R and/or SQL background may find it helpful to see how the pandas syntax compares:
    - Comparison with R / R Libraries: https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_r.html
    - Comparison with SQL: https://pandas.pydata.org/pandas-docs/stable/comparison_with_sql.html
    - SQL Queries: https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_sql.html
- The following are some resources on working with serialized data:
    - Pickle in Python: Object Serialization: https://www.datacamp.com/community/tutorials/pickle-python-tutorial
    - Read RData/RDS files into pandas.DataFrame objects (pyreader): https://github.com/ofajardo/pyreadr
- Additional resources for working with APIs are as follows:
    - Documentation for the requests package: https://requests.readthedocs.io/en/master/
    - HTTP Methods: https://restfulapi.net/http-methods/
    - HTTP Status Codes: https://restfulapi.net/http-status-codes/
- To learn more about regular expressions, consult the following resources:
    - Mastering Python Regular Expressions by Félix López, Víctor Romero: https://www.packtpub.com/application-development/mastering-python-regular-expressions
    - Regular Expression Tutorial — Learn How to Use Regular Expressions: https://www.regular-expressions.info/tutorial.html

# **Practice**