# **Pandas Data Structures**

In [1]:
import numpy as np

In [3]:
data = np.genfromtxt(
    '../Datasets/example_data.csv',
    delimiter=';',
    names=True,
    dtype=None,
    encoding='UTF'
)

data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [4]:
data.shape

(5,)

In [6]:
data.dtype

dtype([('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [8]:
%%timeit
max([row[3] for row in data])

3.69 μs ± 563 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [9]:
data.dtype.names

('time', 'place', 'magType', 'mag', 'alert', 'tsunami')

In [23]:
for i, col in enumerate(data.dtype.names): print(i, "==>", col)

0 ==> time
1 ==> place
2 ==> magType
3 ==> mag
4 ==> alert
5 ==> tsunami

In [24]:
array_dict = {
    col: np.array([row[i] for row in data])
    for i, col in enumerate(data.dtype.names)
}

array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [25]:
%%timeit
array_dict['mag'].max()

1.57 μs ± 81.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [30]:
np.array([
    value[array_dict['mag'].argmax()]
    for key, value in array_dict.items()
])

array(['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
       'mww', '6.7', 'green', '1'], dtype='<U32')

## **Series**

In [31]:
import pandas as pd

In [32]:
place = pd.Series(array_dict['place'], name='place')

place

0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

!['Commonly used series attributes'](../Images/Commonly_used_series_attributes.png)

In [35]:
place.name, place.dtype, place.shape, place.index, place.values

('place',
 dtype('O'),
 (5,),
 RangeIndex(start=0, stop=5, step=1),
 array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype=object))

> **Important note** : For the most part, pandas objects use NumPy arrays for their internal data representations. However, for some data types, pandas builds upon NumPy to create its own arrays (https://pandas.pydata.org/pandas-docs/stable/reference/arrays.html). For this reason, depending on the data type, values can return either a pandas.array or a numpy.array object. Therefore, if we need to ensure we get a specific type back, it is recommended to use the array attribute or to_numpy() method, respectively, instead of values.

## **Index**

In [36]:
place_index = place.index

place_index

RangeIndex(start=0, stop=5, step=1)

In [37]:
place_index.values

array([0, 1, 2, 3, 4])

![Commonly used index attributes](../Images/Commonly_used_index_attributes.png)

In [38]:
place_index.name, place_index.dtype, place_index.shape, place_index.values, place_index.is_unique

(None, dtype('int64'), (5,), array([0, 1, 2, 3, 4]), True)

In [39]:
np.array([1, 0, 1]) + np.array([-1, 1, 1])

array([0, 1, 2])

In [40]:
numbers = np.linspace(0, 10, num=5)

numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
x = pd.Series(numbers) # index is [0, 1, 2, 3, 4]
y = pd.Series(numbers, index=pd.Index([1, 2, 3, 4, 5]))

In [42]:
x

0     0.0
1     2.5
2     5.0
3     7.5
4    10.0
dtype: float64

In [43]:
y

1     0.0
2     2.5
3     5.0
4     7.5
5    10.0
dtype: float64

In [44]:
x + y

0     NaN
1     2.5
2     7.5
3    12.5
4    17.5
5     NaN
dtype: float64

## **DataFrame**

In [45]:
array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [46]:
df = pd.DataFrame(array_dict)

df

,time,place,magType,mag,alert,tsunami
0,2018-10-13 11:10:23.560,"262km NW of Ozernovskiy, Russia",mww,6.7,green,1
1,2018-10-13 04:34:15.580,"25km E of Bitung, Indonesia",mww,5.2,green,0
2,2018-10-13 00:13:46.220,"42km WNW of Sola, Vanuatu",mww,5.7,green,0
3,2018-10-12 21:09:49.240,"13km E of Nueva Concepcion, Guatemala",mww,5.7,green,0
4,2018-10-12 02:52:03.620,"128km SE of Kimbe, Papua New Guinea",mww,5.6,green,1

![Commonly used dataframe attributes](../Images/Commonly_used_dataframe_attributes.png)

In [47]:
df.dtypes

time        object
place       object
magType     object
mag        float64
alert       object
tsunami      int64
dtype: object

In [50]:
df.shape

(5, 6)

In [51]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [49]:
df.columns

Index(['time', 'place', 'magType', 'mag', 'alert', 'tsunami'], dtype='object')

In [48]:
df.values

array([['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
        'mww', 6.7, 'green', 1],
       ['2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww',
        5.2, 'green', 0],
       ['2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww',
        5.7, 'green', 0],
       ['2018-10-12 21:09:49.240',
        '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0],
       ['2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea',
        'mww', 5.6, 'green', 1]], dtype=object)

In [52]:
df.empty

False

In [54]:
df + df

,time,place,magType,mag,alert,tsunami
0,2018-10-13 11:10:23.5602018-10-13 11:10:23.560,"262km NW of Ozernovskiy, Russia262km NW of Oze...",mwwmww,13.4,greengreen,2
1,2018-10-13 04:34:15.5802018-10-13 04:34:15.580,"25km E of Bitung, Indonesia25km E of Bitung, I...",mwwmww,10.4,greengreen,0
2,2018-10-13 00:13:46.2202018-10-13 00:13:46.220,"42km WNW of Sola, Vanuatu42km WNW of Sola, Van...",mwwmww,11.4,greengreen,0
3,2018-10-12 21:09:49.2402018-10-12 21:09:49.240,"13km E of Nueva Concepcion, Guatemala13km E of...",mwwmww,11.4,greengreen,0
4,2018-10-12 02:52:03.6202018-10-12 02:52:03.620,"128km SE of Kimbe, Papua New Guinea128km SE of...",mwwmww,11.2,greengreen,2